-- V10__seed_strategy_cards.sql
INSERT INTO strategy_card_pool (id, card_type, tone, min_score, max_score, required_tags, blocked_tags, conditions_json, title_template, body_template, footer_template, weight, priority, tags) VALUES
  (1, 'BUY_INTENSITY', 'COOL', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 4, 1, 'LOW,RESPONSIBLE'),
  (2, 'BUY_INTENSITY', 'WARM', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 1, 3, 'LOW,RESPONSIBLE'),
  (3, 'BUY_INTENSITY', 'COOL', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 1, 4, 'LOW,RESPONSIBLE'),
  (4, 'BUY_INTENSITY', 'DRY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 4, 5, 'LOW,RESPONSIBLE'),
  (5, 'BUY_INTENSITY', 'ANY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 2, 3, 'LOW,RESPONSIBLE'),
  (6, 'BUY_INTENSITY', 'DRY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 4, 3, 'LOW,RESPONSIBLE'),
  (7, 'BUY_INTENSITY', 'FUNNY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 3, 3, 'LOW,RESPONSIBLE'),
  (8, 'BUY_INTENSITY', 'COOL', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 4, 2, 'LOW,RESPONSIBLE'),
  (9, 'BUY_INTENSITY', 'FUNNY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 2, 5, 'LOW,RESPONSIBLE'),
  (10, 'BUY_INTENSITY', 'FUNNY', 0, 60, 'DONT_BUY_TODAY', NULL, '{"all": [{"type": "axis", "axis": "IMPULSIVITY", "op": ">=", "value": 40}]}', '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 2, 1, 'LOW,RESPONSIBLE'),
  (11, 'BUY_INTENSITY', 'FUNNY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 2, 5, 'LOW,RESPONSIBLE'),
  (12, 'BUY_INTENSITY', 'WARM', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 2, 2, 'LOW,RESPONSIBLE'),
  (13, 'BUY_INTENSITY', 'DRY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 3, 2, 'LOW,RESPONSIBLE'),
  (14, 'BUY_INTENSITY', 'COOL', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 2, 2, 'LOW,RESPONSIBLE'),
  (15, 'BUY_INTENSITY', 'FUNNY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 4, 3, 'LOW,RESPONSIBLE'),
  (16, 'BUY_INTENSITY', 'ANY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 3, 2, 'LOW,RESPONSIBLE'),
  (17, 'BUY_INTENSITY', 'COOL', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 3, 2, 'LOW,RESPONSIBLE'),
  (18, 'BUY_INTENSITY', 'FUNNY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '추천은 {BUY_COUNT}입니다. {REASON_PHRASE}', '멈춤 규칙: {STOP_RULE}', 3, 0, 'LOW,RESPONSIBLE'),
  (19, 'BUY_INTENSITY', 'FUNNY', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 4, 4, 'INTENSITY'),
  (20, 'BUY_INTENSITY', 'DRY', 30, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": ">=", "value": 65}]}', '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 4, 5, 'INTENSITY'),
  (21, 'BUY_INTENSITY', 'DRY', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 2, 4, 'INTENSITY'),
  (22, 'BUY_INTENSITY', 'WARM', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 4, 1, 'INTENSITY'),
  (23, 'BUY_INTENSITY', 'COOL', 30, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": ">=", "value": 65}]}', '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 4, 3, 'INTENSITY'),
  (24, 'BUY_INTENSITY', 'ANY', 30, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "RISK", "op": ">=", "value": 40}]}', '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 2, 5, 'INTENSITY'),
  (25, 'BUY_INTENSITY', 'FUNNY', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 1, 3, 'INTENSITY'),
  (26, 'BUY_INTENSITY', 'COOL', 30, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "STABILITY", "op": ">=", "value": 40}]}', '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 4, 3, 'INTENSITY'),
  (27, 'BUY_INTENSITY', 'FUNNY', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 3, 3, 'INTENSITY'),
  (28, 'BUY_INTENSITY', 'COOL', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 2, 5, 'INTENSITY'),
  (29, 'BUY_INTENSITY', 'COOL', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 2, 0, 'INTENSITY'),
  (30, 'BUY_INTENSITY', 'WARM', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 2, 0, 'INTENSITY'),
  (31, 'BUY_INTENSITY', 'ANY', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 1, 3, 'INTENSITY'),
  (32, 'BUY_INTENSITY', 'FUNNY', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 4, 3, 'INTENSITY'),
  (33, 'BUY_INTENSITY', 'ANY', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 3, 2, 'INTENSITY'),
  (34, 'BUY_INTENSITY', 'WARM', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 1, 4, 'INTENSITY'),
  (35, 'BUY_INTENSITY', 'ANY', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 4, 3, 'INTENSITY'),
  (36, 'BUY_INTENSITY', 'COOL', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 1, 2, 'INTENSITY'),
  (37, 'BUY_INTENSITY', 'WARM', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 3, 5, 'INTENSITY'),
  (38, 'BUY_INTENSITY', 'COOL', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 1, 4, 'INTENSITY'),
  (39, 'BUY_INTENSITY', 'DRY', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 3, 4, 'INTENSITY'),
  (40, 'BUY_INTENSITY', 'COOL', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 2, 0, 'INTENSITY'),
  (41, 'BUY_INTENSITY', 'ANY', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 2, 3, 'INTENSITY'),
  (42, 'BUY_INTENSITY', 'DRY', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 2, 5, 'INTENSITY'),
  (43, 'BUY_INTENSITY', 'ANY', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 2, 0, 'INTENSITY'),
  (44, 'BUY_INTENSITY', 'DRY', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 2, 1, 'INTENSITY'),
  (45, 'BUY_INTENSITY', 'DRY', 30, 100, NULL, NULL, NULL, '오늘 구매 강도: {INTENSITY_WORD}', '권장 수량: {BUY_COUNT}. {REASON_PHRASE}', '한도 지키기: {BUDGET_SMALL}', 4, 0, 'INTENSITY'),
  (46, 'BUDGET_CAP', 'FUNNY', 0, 70, 'MONEY_TIGHT', NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 3, 2, 'BUDGET,RESPONSIBLE'),
  (47, 'BUDGET_CAP', 'WARM', 0, 70, 'MONEY_TIGHT', NULL, '{"all": [{"type": "axis", "axis": "STABILITY", "op": "<=", "value": 35}]}', '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 1, 0, 'BUDGET,RESPONSIBLE'),
  (48, 'BUDGET_CAP', 'DRY', 0, 70, 'MONEY_TIGHT', NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 4, 2, 'BUDGET,RESPONSIBLE'),
  (49, 'BUDGET_CAP', 'WARM', 0, 70, 'MONEY_TIGHT', NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 4, 0, 'BUDGET,RESPONSIBLE'),
  (50, 'BUDGET_CAP', 'ANY', 0, 70, 'MONEY_TIGHT', NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 2, 'BUDGET,RESPONSIBLE'),
  (51, 'BUDGET_CAP', 'DRY', 0, 70, 'MONEY_TIGHT', NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 3, 1, 'BUDGET,RESPONSIBLE'),
  (52, 'BUDGET_CAP', 'WARM', 0, 70, 'MONEY_TIGHT', NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 3, 'BUDGET,RESPONSIBLE'),
  (53, 'BUDGET_CAP', 'DRY', 0, 70, 'MONEY_TIGHT', NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 2, 'BUDGET,RESPONSIBLE'),
  (54, 'BUDGET_CAP', 'WARM', 0, 70, 'MONEY_TIGHT', NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 4, 5, 'BUDGET,RESPONSIBLE'),
  (55, 'BUDGET_CAP', 'WARM', 0, 70, 'MONEY_TIGHT', NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 1, 2, 'BUDGET,RESPONSIBLE'),
  (56, 'BUDGET_CAP', 'DRY', 0, 70, 'MONEY_TIGHT', NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 1, 4, 'BUDGET,RESPONSIBLE'),
  (57, 'BUDGET_CAP', 'ANY', 0, 70, 'MONEY_TIGHT', NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 3, 1, 'BUDGET,RESPONSIBLE'),
  (58, 'BUDGET_CAP', 'DRY', 0, 70, 'MONEY_TIGHT', NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 3, 'BUDGET,RESPONSIBLE'),
  (59, 'BUDGET_CAP', 'ANY', 0, 70, 'MONEY_TIGHT', NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 4, 2, 'BUDGET,RESPONSIBLE'),
  (60, 'BUDGET_CAP', 'COOL', 0, 70, 'MONEY_TIGHT', NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 4, 4, 'BUDGET,RESPONSIBLE'),
  (61, 'BUDGET_CAP', 'DRY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 0, 'BUDGET,RESPONSIBLE'),
  (62, 'BUDGET_CAP', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 5, 'BUDGET,RESPONSIBLE'),
  (63, 'BUDGET_CAP', 'WARM', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 3, 'BUDGET,RESPONSIBLE'),
  (64, 'BUDGET_CAP', 'ANY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 0, 'BUDGET,RESPONSIBLE'),
  (65, 'BUDGET_CAP', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 1, 3, 'BUDGET,RESPONSIBLE'),
  (66, 'BUDGET_CAP', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 3, 3, 'BUDGET,RESPONSIBLE'),
  (67, 'BUDGET_CAP', 'DRY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 2, 'BUDGET,RESPONSIBLE'),
  (68, 'BUDGET_CAP', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 0, 'BUDGET,RESPONSIBLE'),
  (69, 'BUDGET_CAP', 'WARM', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 4, 4, 'BUDGET,RESPONSIBLE'),
  (70, 'BUDGET_CAP', 'WARM', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 1, 'BUDGET,RESPONSIBLE'),
  (71, 'BUDGET_CAP', 'DRY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 4, 0, 'BUDGET,RESPONSIBLE'),
  (72, 'BUDGET_CAP', 'ANY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 1, 1, 'BUDGET,RESPONSIBLE'),
  (73, 'BUDGET_CAP', 'ANY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 3, 'BUDGET,RESPONSIBLE'),
  (74, 'BUDGET_CAP', 'COOL', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 3, 5, 'BUDGET,RESPONSIBLE'),
  (75, 'BUDGET_CAP', 'DRY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 4, 2, 'BUDGET,RESPONSIBLE'),
  (76, 'BUDGET_CAP', 'WARM', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "IMPULSIVITY", "op": ">=", "value": 65}]}', '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 4, 0, 'BUDGET,RESPONSIBLE'),
  (77, 'BUDGET_CAP', 'COOL', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "FIN_EASE", "op": "<=", "value": 70}]}', '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 4, 1, 'BUDGET,RESPONSIBLE'),
  (78, 'BUDGET_CAP', 'WARM', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 3, 'BUDGET,RESPONSIBLE'),
  (79, 'BUDGET_CAP', 'DRY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "IMPULSIVITY", "op": ">=", "value": 75}]}', '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 1, 2, 'BUDGET,RESPONSIBLE'),
  (80, 'BUDGET_CAP', 'COOL', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 3, 1, 'BUDGET,RESPONSIBLE'),
  (81, 'BUDGET_CAP', 'WARM', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 1, 0, 'BUDGET,RESPONSIBLE'),
  (82, 'BUDGET_CAP', 'DRY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 1, 0, 'BUDGET,RESPONSIBLE'),
  (83, 'BUDGET_CAP', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 4, 5, 'BUDGET,RESPONSIBLE'),
  (84, 'BUDGET_CAP', 'DRY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 4, 'BUDGET,RESPONSIBLE'),
  (85, 'BUDGET_CAP', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 3, 0, 'BUDGET,RESPONSIBLE'),
  (86, 'BUDGET_CAP', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 4, 1, 'BUDGET,RESPONSIBLE'),
  (87, 'BUDGET_CAP', 'COOL', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 0, 'BUDGET,RESPONSIBLE'),
  (88, 'BUDGET_CAP', 'ANY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 0, 'BUDGET,RESPONSIBLE'),
  (89, 'BUDGET_CAP', 'DRY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 4, 'BUDGET,RESPONSIBLE'),
  (90, 'BUDGET_CAP', 'DRY', 0, 100, NULL, NULL, NULL, '오늘의 추천 한도', '예산은 {BUDGET_SMALL}로 캡! {REASON_PHRASE}', '추가 구매는 {STOP_RULE}', 2, 2, 'BUDGET,RESPONSIBLE'),
  (91, 'TIMING', 'FUNNY', 50, 100, 'ENERGY_HIGH_TAG', NULL, '{"all": [{"type": "axis", "axis": "IMPULSIVITY", "op": ">=", "value": 40}]}', '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 3, 5, 'TIMING'),
  (92, 'TIMING', 'ANY', 50, 100, 'ENERGY_HIGH_TAG', NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 4, 1, 'TIMING'),
  (93, 'TIMING', 'FUNNY', 50, 100, 'ENERGY_HIGH_TAG', NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 2, 0, 'TIMING'),
  (94, 'TIMING', 'COOL', 50, 100, 'ENERGY_HIGH_TAG', NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 4, 3, 'TIMING'),
  (95, 'TIMING', 'FUNNY', 50, 100, 'ENERGY_HIGH_TAG', NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 3, 5, 'TIMING'),
  (96, 'TIMING', 'WARM', 50, 100, 'ENERGY_HIGH_TAG', NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 1, 2, 'TIMING'),
  (97, 'TIMING', 'FUNNY', 50, 100, 'ENERGY_HIGH_TAG', NULL, '{"all": [{"type": "axis", "axis": "FIN_EASE", "op": "<=", "value": 75}]}', '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 2, 2, 'TIMING'),
  (98, 'TIMING', 'COOL', 50, 100, 'ENERGY_HIGH_TAG', NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 4, 3, 'TIMING'),
  (99, 'TIMING', 'ANY', 50, 100, 'ENERGY_HIGH_TAG', NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 4, 0, 'TIMING'),
  (100, 'TIMING', 'COOL', 50, 100, 'ENERGY_HIGH_TAG', NULL, '{"all": [{"type": "axis", "axis": "STABILITY", "op": "<=", "value": 40}]}', '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 3, 3, 'TIMING'),
  (101, 'TIMING', 'COOL', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 3, 1, 'TIMING'),
  (102, 'TIMING', 'COOL', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 3, 5, 'TIMING'),
  (103, 'TIMING', 'WARM', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 1, 5, 'TIMING'),
  (104, 'TIMING', 'ANY', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 3, 4, 'TIMING'),
  (105, 'TIMING', 'COOL', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 1, 5, 'TIMING'),
  (106, 'TIMING', 'WARM', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 4, 4, 'TIMING'),
  (107, 'TIMING', 'WARM', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 4, 0, 'TIMING'),
  (108, 'TIMING', 'WARM', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 3, 1, 'TIMING'),
  (109, 'TIMING', 'ANY', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 2, 5, 'TIMING'),
  (110, 'TIMING', 'ANY', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 4, 1, 'TIMING'),
  (111, 'TIMING', 'ANY', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 4, 1, 'TIMING'),
  (112, 'TIMING', 'FUNNY', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 4, 5, 'TIMING'),
  (113, 'TIMING', 'ANY', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 1, 4, 'TIMING'),
  (114, 'TIMING', 'ANY', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 4, 2, 'TIMING'),
  (115, 'TIMING', 'FUNNY', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 4, 5, 'TIMING'),
  (116, 'TIMING', 'FUNNY', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 4, 4, 'TIMING'),
  (117, 'TIMING', 'ANY', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 4, 5, 'TIMING'),
  (118, 'TIMING', 'ANY', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 4, 1, 'TIMING'),
  (119, 'TIMING', 'COOL', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 1, 5, 'TIMING'),
  (120, 'TIMING', 'COOL', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "RISK", "op": ">=", "value": 40}]}', '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 4, 2, 'TIMING'),
  (121, 'TIMING', 'ANY', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 3, 5, 'TIMING'),
  (122, 'TIMING', 'WARM', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 2, 2, 'TIMING'),
  (123, 'TIMING', 'WARM', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 2, 3, 'TIMING'),
  (124, 'TIMING', 'COOL', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 1, 4, 'TIMING'),
  (125, 'TIMING', 'WARM', 0, 100, NULL, NULL, NULL, '추천 타이밍', '{TIME_WINDOW}에만 가볍게. {REASON_PHRASE}', '타이밍 끝나면 {STOP_RULE}', 1, 3, 'TIMING'),
  (126, 'RULE', 'DRY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 2, 3, 'RULE'),
  (127, 'RULE', 'FUNNY', 0, 60, 'DONT_BUY_TODAY', NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": "<=", "value": 65}]}', '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 2, 4, 'RULE'),
  (128, 'RULE', 'WARM', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 3, 4, 'RULE'),
  (129, 'RULE', 'ANY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 3, 0, 'RULE'),
  (130, 'RULE', 'DRY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 1, 1, 'RULE'),
  (131, 'RULE', 'ANY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 1, 2, 'RULE'),
  (132, 'RULE', 'COOL', 0, 60, 'DONT_BUY_TODAY', NULL, '{"all": [{"type": "axis", "axis": "RISK", "op": "<=", "value": 75}]}', '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 1, 0, 'RULE'),
  (133, 'RULE', 'COOL', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 3, 4, 'RULE'),
  (134, 'RULE', 'ANY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 4, 2, 'RULE'),
  (135, 'RULE', 'DRY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 3, 4, 'RULE'),
  (136, 'RULE', 'DRY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 2, 3, 'RULE'),
  (137, 'RULE', 'DRY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 1, 0, 'RULE'),
  (138, 'RULE', 'FUNNY', 0, 60, 'DONT_BUY_TODAY', NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": ">=", "value": 75}]}', '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 1, 4, 'RULE'),
  (139, 'RULE', 'COOL', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 2, 5, 'RULE'),
  (140, 'RULE', 'DRY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 4, 0, 'RULE'),
  (141, 'RULE', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 2, 5, 'RULE'),
  (142, 'RULE', 'WARM', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 2, 4, 'RULE'),
  (143, 'RULE', 'COOL', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 2, 0, 'RULE'),
  (144, 'RULE', 'DRY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "STABILITY", "op": "<=", "value": 75}]}', '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 2, 1, 'RULE'),
  (145, 'RULE', 'DRY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": ">=", "value": 65}]}', '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 1, 4, 'RULE'),
  (146, 'RULE', 'COOL', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 4, 3, 'RULE'),
  (147, 'RULE', 'WARM', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 4, 4, 'RULE'),
  (148, 'RULE', 'ANY', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 4, 2, 'RULE'),
  (149, 'RULE', 'DRY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "STABILITY", "op": ">=", "value": 75}]}', '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 3, 3, 'RULE'),
  (150, 'RULE', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 1, 3, 'RULE'),
  (151, 'RULE', 'COOL', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": ">=", "value": 35}]}', '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 2, 5, 'RULE'),
  (152, 'RULE', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 1, 3, 'RULE'),
  (153, 'RULE', 'DRY', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 4, 3, 'RULE'),
  (154, 'RULE', 'DRY', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 3, 3, 'RULE'),
  (155, 'RULE', 'COOL', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 4, 4, 'RULE'),
  (156, 'RULE', 'COOL', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 3, 3, 'RULE'),
  (157, 'RULE', 'COOL', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 2, 2, 'RULE'),
  (158, 'RULE', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 3, 1, 'RULE'),
  (159, 'RULE', 'ANY', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 3, 0, 'RULE'),
  (160, 'RULE', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 3, 5, 'RULE'),
  (161, 'RULE', 'ANY', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 3, 0, 'RULE'),
  (162, 'RULE', 'COOL', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 1, 2, 'RULE'),
  (163, 'RULE', 'WARM', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 3, 4, 'RULE'),
  (164, 'RULE', 'ANY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": ">=", "value": 75}]}', '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 2, 5, 'RULE'),
  (165, 'RULE', 'ANY', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 2, 1, 'RULE'),
  (166, 'RULE', 'DRY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "RISK", "op": "<=", "value": 70}]}', '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 1, 4, 'RULE'),
  (167, 'RULE', 'WARM', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 3, 5, 'RULE'),
  (168, 'RULE', 'DRY', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 3, 2, 'RULE'),
  (169, 'RULE', 'ANY', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 1, 2, 'RULE'),
  (170, 'RULE', 'WARM', 0, 100, NULL, NULL, NULL, '오늘의 멈춤 규칙', '{STOP_RULE}을 오늘의 기본 룰로 설정하세요.', '보조 룰: {BUDGET_SMALL}', 4, 2, 'RULE'),
  (171, 'SAFETY', 'WARM', 0, 65, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 3, 5, 'SAFETY,RESPONSIBLE'),
  (172, 'SAFETY', 'FUNNY', 0, 65, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 1, 4, 'SAFETY,RESPONSIBLE'),
  (173, 'SAFETY', 'DRY', 0, 65, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 4, 3, 'SAFETY,RESPONSIBLE'),
  (174, 'SAFETY', 'WARM', 0, 65, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 3, 2, 'SAFETY,RESPONSIBLE'),
  (175, 'SAFETY', 'ANY', 0, 65, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 3, 1, 'SAFETY,RESPONSIBLE'),
  (176, 'SAFETY', 'DRY', 0, 65, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 1, 5, 'SAFETY,RESPONSIBLE'),
  (177, 'SAFETY', 'DRY', 0, 65, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 1, 2, 'SAFETY,RESPONSIBLE'),
  (178, 'SAFETY', 'COOL', 0, 65, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 1, 1, 'SAFETY,RESPONSIBLE'),
  (179, 'SAFETY', 'FUNNY', 0, 65, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 4, 3, 'SAFETY,RESPONSIBLE'),
  (180, 'SAFETY', 'COOL', 0, 65, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 2, 3, 'SAFETY,RESPONSIBLE'),
  (181, 'SAFETY', 'WARM', 0, 65, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 3, 4, 'SAFETY,RESPONSIBLE'),
  (182, 'SAFETY', 'COOL', 0, 65, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 2, 0, 'SAFETY,RESPONSIBLE'),
  (183, 'SAFETY', 'FUNNY', 0, 65, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 4, 2, 'SAFETY,RESPONSIBLE'),
  (184, 'SAFETY', 'COOL', 0, 65, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 2, 3, 'SAFETY,RESPONSIBLE'),
  (185, 'SAFETY', 'FUNNY', 0, 65, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 3, 2, 'SAFETY,RESPONSIBLE'),
  (186, 'SAFETY', 'FUNNY', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 3, 0, 'SAFETY,RESPONSIBLE'),
  (187, 'SAFETY', 'COOL', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 2, 2, 'SAFETY,RESPONSIBLE'),
  (188, 'SAFETY', 'DRY', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 1, 5, 'SAFETY,RESPONSIBLE'),
  (189, 'SAFETY', 'DRY', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 2, 2, 'SAFETY,RESPONSIBLE'),
  (190, 'SAFETY', 'COOL', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 2, 3, 'SAFETY,RESPONSIBLE'),
  (191, 'SAFETY', 'ANY', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 3, 1, 'SAFETY,RESPONSIBLE'),
  (192, 'SAFETY', 'WARM', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 1, 5, 'SAFETY,RESPONSIBLE'),
  (193, 'SAFETY', 'FUNNY', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 3, 3, 'SAFETY,RESPONSIBLE'),
  (194, 'SAFETY', 'COOL', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 2, 3, 'SAFETY,RESPONSIBLE'),
  (195, 'SAFETY', 'FUNNY', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 2, 2, 'SAFETY,RESPONSIBLE'),
  (196, 'SAFETY', 'DRY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "STABILITY", "op": "<=", "value": 40}]}', '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 3, 4, 'SAFETY,RESPONSIBLE'),
  (197, 'SAFETY', 'FUNNY', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 4, 5, 'SAFETY,RESPONSIBLE'),
  (198, 'SAFETY', 'DRY', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 3, 1, 'SAFETY,RESPONSIBLE'),
  (199, 'SAFETY', 'WARM', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 3, 1, 'SAFETY,RESPONSIBLE'),
  (200, 'SAFETY', 'COOL', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 4, 4, 'SAFETY,RESPONSIBLE');

INSERT INTO strategy_card_pool (id, card_type, tone, min_score, max_score, required_tags, blocked_tags, conditions_json, title_template, body_template, footer_template, weight, priority, tags) VALUES
  (201, 'SAFETY', 'DRY', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 1, 5, 'SAFETY,RESPONSIBLE'),
  (202, 'SAFETY', 'FUNNY', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 2, 3, 'SAFETY,RESPONSIBLE'),
  (203, 'SAFETY', 'FUNNY', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 3, 3, 'SAFETY,RESPONSIBLE'),
  (204, 'SAFETY', 'WARM', 0, 100, NULL, NULL, NULL, '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 3, 5, 'SAFETY,RESPONSIBLE'),
  (205, 'SAFETY', 'FUNNY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "FIN_EASE", "op": ">=", "value": 70}]}', '과몰입 방지 장치', '{SAFETY_PHRASE} {REASON_PHRASE}', '오늘의 안전장치: {STOP_RULE}', 1, 1, 'SAFETY,RESPONSIBLE'),
  (206, 'DO', 'COOL', 0, 80, 'STRESS_HIGH', NULL, '{"all": [{"type": "axis", "axis": "IMPULSIVITY", "op": ">=", "value": 70}]}', '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 3, 1, 'DO'),
  (207, 'DO', 'DRY', 0, 80, 'STRESS_HIGH', NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 2, 3, 'DO'),
  (208, 'DO', 'DRY', 0, 80, 'STRESS_HIGH', NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 4, 2, 'DO'),
  (209, 'DO', 'DRY', 0, 80, 'STRESS_HIGH', NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 4, 2, 'DO'),
  (210, 'DO', 'FUNNY', 0, 80, 'STRESS_HIGH', NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 2, 1, 'DO'),
  (211, 'DO', 'COOL', 0, 80, 'STRESS_HIGH', NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 4, 2, 'DO'),
  (212, 'DO', 'COOL', 0, 80, 'STRESS_HIGH', NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": ">=", "value": 40}]}', '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 1, 0, 'DO'),
  (213, 'DO', 'ANY', 0, 80, 'STRESS_HIGH', NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 4, 4, 'DO'),
  (214, 'DO', 'DRY', 0, 100, NULL, NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 3, 4, 'DO'),
  (215, 'DO', 'WARM', 0, 100, NULL, NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 2, 4, 'DO'),
  (216, 'DO', 'WARM', 0, 100, NULL, NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 2, 0, 'DO'),
  (217, 'DO', 'ANY', 0, 100, NULL, NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 3, 2, 'DO'),
  (218, 'DO', 'WARM', 0, 100, NULL, NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 3, 1, 'DO'),
  (219, 'DO', 'FUNNY', 0, 100, NULL, NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 1, 2, 'DO'),
  (220, 'DO', 'DRY', 0, 100, NULL, NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 4, 4, 'DO'),
  (221, 'DO', 'DRY', 0, 100, NULL, NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 1, 2, 'DO'),
  (222, 'DO', 'DRY', 0, 100, NULL, NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 4, 3, 'DO'),
  (223, 'DO', 'DRY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": "<=", "value": 70}]}', '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 1, 4, 'DO'),
  (224, 'DO', 'FUNNY', 0, 100, NULL, NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 4, 1, 'DO'),
  (225, 'DO', 'DRY', 0, 100, NULL, NULL, NULL, '구매 전 하면 좋은 행동', '{DO_ACTION}', '끝나면 {STOP_RULE}', 1, 3, 'DO'),
  (226, 'FUN_MISSION', 'ANY', 0, 100, NULL, NULL, NULL, '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 2, 1, 'FUN'),
  (227, 'FUN_MISSION', 'COOL', 0, 100, NULL, NULL, NULL, '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 1, 3, 'FUN'),
  (228, 'FUN_MISSION', 'ANY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "IMPULSIVITY", "op": ">=", "value": 40}]}', '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 3, 4, 'FUN'),
  (229, 'FUN_MISSION', 'ANY', 0, 100, NULL, NULL, NULL, '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 3, 4, 'FUN'),
  (230, 'FUN_MISSION', 'WARM', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "RISK", "op": "<=", "value": 70}]}', '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 2, 5, 'FUN'),
  (231, 'FUN_MISSION', 'DRY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": ">=", "value": 65}]}', '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 3, 3, 'FUN'),
  (232, 'FUN_MISSION', 'ANY', 0, 100, NULL, NULL, NULL, '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 2, 2, 'FUN'),
  (233, 'FUN_MISSION', 'DRY', 0, 100, NULL, NULL, NULL, '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 3, 4, 'FUN'),
  (234, 'FUN_MISSION', 'DRY', 0, 100, NULL, NULL, NULL, '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 3, 1, 'FUN'),
  (235, 'FUN_MISSION', 'FUNNY', 0, 100, NULL, NULL, NULL, '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 1, 0, 'FUN'),
  (236, 'FUN_MISSION', 'COOL', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": ">=", "value": 35}]}', '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 4, 3, 'FUN'),
  (237, 'FUN_MISSION', 'DRY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": ">=", "value": 70}]}', '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 4, 4, 'FUN'),
  (238, 'FUN_MISSION', 'WARM', 0, 100, NULL, NULL, NULL, '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 3, 0, 'FUN'),
  (239, 'FUN_MISSION', 'FUNNY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "FIN_EASE", "op": ">=", "value": 70}]}', '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 1, 4, 'FUN'),
  (240, 'FUN_MISSION', 'WARM', 0, 100, NULL, NULL, NULL, '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 2, 4, 'FUN'),
  (241, 'FUN_MISSION', 'DRY', 0, 100, NULL, NULL, NULL, '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 1, 4, 'FUN'),
  (242, 'FUN_MISSION', 'COOL', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": ">=", "value": 70}]}', '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 4, 2, 'FUN'),
  (243, 'FUN_MISSION', 'FUNNY', 0, 100, NULL, NULL, NULL, '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 3, 2, 'FUN'),
  (244, 'FUN_MISSION', 'FUNNY', 0, 100, NULL, NULL, NULL, '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 2, 2, 'FUN'),
  (245, 'FUN_MISSION', 'WARM', 0, 100, NULL, NULL, NULL, '재미 미션 카드', '{FUN_MISSION_TEXT}', '미션 성공 후 {STOP_RULE}', 4, 3, 'FUN');
