-- V11__seed_strategy_slots.sql
INSERT INTO strategy_slot_pool (id, slot_key, tone, text, weight) VALUES
  (1, 'BUDGET_SMALL', 'FUNNY', '3,000원 이내', 2),
  (2, 'BUDGET_SMALL', 'FUNNY', '오늘은 최소', 3),
  (3, 'BUDGET_SMALL', 'ANY', '딱 소액', 2),
  (4, 'BUDGET_SMALL', 'COOL', '간식 정도', 1),
  (5, 'BUDGET_SMALL', 'DRY', '딱 소액', 1),
  (6, 'BUDGET_SMALL', 'ANY', '1,000~2,000원', 2),
  (7, 'BUDGET_SMALL', 'COOL', '5,000원 이내', 4),
  (8, 'BUDGET_SMALL', 'DRY', '0원(PASS) 😎', 2),
  (9, 'BUDGET_SMALL', 'WARM', '3,000원 이내', 1),
  (10, 'BUDGET_SMALL', 'WARM', '딱 소액', 3),
  (11, 'BUDGET_SMALL', 'ANY', '3,000원 이내', 1),
  (12, 'BUDGET_SMALL', 'DRY', '5,000원 이내', 2),
  (13, 'BUDGET_SMALL', 'DRY', '1,000~2,000원', 4),
  (14, 'BUDGET_SMALL', 'WARM', '5,000원 이내', 2),
  (15, 'BUDGET_SMALL', 'FUNNY', '2,000~3,000원', 2),
  (16, 'BUDGET_SMALL', 'COOL', '0원(PASS) (추천)', 2),
  (17, 'BUDGET_SMALL', 'WARM', '1,000~2,000원', 1),
  (18, 'BUDGET_SMALL', 'FUNNY', '한 장 값만 😎', 2),
  (19, 'BUDGET_SMALL', 'FUNNY', '오늘은 최소', 1),
  (20, 'BUDGET_SMALL', 'DRY', '딱 소액', 1),
  (21, 'BUDGET_SMALL', 'DRY', '3,000원 이내', 2),
  (22, 'BUDGET_SMALL', 'COOL', '0원(PASS)', 2),
  (23, 'BUY_COUNT', 'ANY', '1장', 1),
  (24, 'BUY_COUNT', 'FUNNY', '0장(쉬기)', 2),
  (25, 'BUY_COUNT', 'ANY', '0장(쉬기)', 4),
  (26, 'BUY_COUNT', 'DRY', 'PASS', 4),
  (27, 'BUY_COUNT', 'COOL', 'PASS', 3),
  (28, 'BUY_COUNT', 'COOL', '한 장 후 종료!', 2),
  (29, 'BUY_COUNT', 'DRY', '1장만 가볍게', 4),
  (30, 'BUY_COUNT', 'ANY', '0~1장 🙂', 2),
  (31, 'BUY_COUNT', 'DRY', '2장(최대)', 2),
  (32, 'BUY_COUNT', 'DRY', '0장(쉬기)', 3),
  (33, 'BUY_COUNT', 'FUNNY', '2~3장은 금지', 3),
  (34, 'BUY_COUNT', 'WARM', '딱 1회', 3),
  (35, 'BUY_COUNT', 'ANY', '1장', 3),
  (36, 'BUY_COUNT', 'DRY', '한 장 후 종료', 1),
  (37, 'BUY_COUNT', 'WARM', 'PASS', 1),
  (38, 'BUY_COUNT', 'DRY', '2장(최대)', 4),
  (39, 'BUY_COUNT', 'COOL', '1~2장', 1),
  (40, 'BUY_COUNT', 'DRY', '1장', 2),
  (41, 'BUY_COUNT', 'COOL', '딱 1회!', 3),
  (42, 'BUY_COUNT', 'ANY', '딱 1회', 4),
  (43, 'BUY_COUNT', 'DRY', '1장만 가볍게 (추천)', 4),
  (44, 'BUY_COUNT', 'FUNNY', 'PASS 🙂', 4),
  (45, 'TIME_WINDOW', 'DRY', '맑을 때만 짧게', 2),
  (46, 'TIME_WINDOW', 'COOL', '점심 전후 15분', 3),
  (47, 'TIME_WINDOW', 'WARM', '맑을 때만 짧게', 4),
  (48, 'TIME_WINDOW', 'COOL', '바람 쐬는 길에', 2),
  (49, 'TIME_WINDOW', 'ANY', '오늘 한 번만', 4),
  (50, 'TIME_WINDOW', 'WARM', '점심 전후 15분', 4),
  (51, 'TIME_WINDOW', 'DRY', '가장 한가한 시간', 3),
  (52, 'TIME_WINDOW', 'FUNNY', '점심 전후 15분!', 2),
  (53, 'TIME_WINDOW', 'FUNNY', '맑을 때만 짧게', 3),
  (54, 'TIME_WINDOW', 'FUNNY', '바람 쐬는 길에', 2),
  (55, 'TIME_WINDOW', 'COOL', '약속 전후는 피하기', 1),
  (56, 'TIME_WINDOW', 'FUNNY', '점심 전후 15분', 2),
  (57, 'TIME_WINDOW', 'ANY', '오늘 한 번만', 3),
  (58, 'TIME_WINDOW', 'DRY', '가장 한가한 시간', 3),
  (59, 'TIME_WINDOW', 'COOL', '가장 한가한 시간', 2),
  (60, 'TIME_WINDOW', 'WARM', '피곤할 땐 금지', 2),
  (61, 'TIME_WINDOW', 'COOL', '맑을 때만 짧게', 3),
  (62, 'TIME_WINDOW', 'WARM', '피곤할 땐 금지', 3),
  (63, 'TIME_WINDOW', 'COOL', '집 가는 길에만', 3),
  (64, 'TIME_WINDOW', 'DRY', '맑을 때만 짧게', 1),
  (65, 'TIME_WINDOW', 'DRY', '저녁 30분 안에', 4),
  (66, 'TIME_WINDOW', 'WARM', '가장 한가한 시간', 4),
  (67, 'STOP_RULE', 'FUNNY', '친구에게 ‘끝’ 선언', 2),
  (68, 'STOP_RULE', 'ANY', '한 번만 방문!', 1),
  (69, 'STOP_RULE', 'COOL', '추가 구매 금지', 1),
  (70, 'STOP_RULE', 'FUNNY', '추가 구매 금지', 1),
  (71, 'STOP_RULE', 'WARM', '예산 넘으면 즉시 스톱 😎', 4),
  (72, 'STOP_RULE', 'FUNNY', '추가 구매 금지', 1),
  (73, 'STOP_RULE', 'DRY', '추가 구매 금지', 4),
  (74, 'STOP_RULE', 'DRY', '한 번만 방문 😎', 4),
  (75, 'STOP_RULE', 'FUNNY', '친구에게 ‘끝’ 선언', 3),
  (76, 'STOP_RULE', 'WARM', '구매 후 바로 귀가', 1),
  (77, 'STOP_RULE', 'ANY', '10초 멈춤 후 결정', 3),
  (78, 'STOP_RULE', 'COOL', '친구에게 ‘끝’ 선언', 1),
  (79, 'STOP_RULE', 'FUNNY', '딱 1장만', 4),
  (80, 'STOP_RULE', 'DRY', '구매 후 바로 귀가', 2),
  (81, 'STOP_RULE', 'COOL', '방문 1회로 종료', 2),
  (82, 'STOP_RULE', 'COOL', '방문 1회로 종료', 2),
  (83, 'STOP_RULE', 'DRY', '한 번만 방문 😎', 4),
  (84, 'STOP_RULE', 'ANY', '오늘은 PASS도 OK', 3),
  (85, 'STOP_RULE', 'DRY', '딱 1장만', 4),
  (86, 'STOP_RULE', 'WARM', '딱 1장만!', 3),
  (87, 'STOP_RULE', 'DRY', '딱 1장만', 1),
  (88, 'STOP_RULE', 'FUNNY', '방문 1회로 종료', 3),
  (89, 'REASON_PHRASE', 'WARM', '작은 성공 경험이 더 오래 가기 때문이에요.', 3),
  (90, 'REASON_PHRASE', 'COOL', '작은 성공 경험이 더 오래 가기 때문이에요.', 4),
  (91, 'REASON_PHRASE', 'WARM', '충동이 올라오면 판단이 흔들리기 때문이에요.', 4),
  (92, 'REASON_PHRASE', 'FUNNY', '한도를 넘기면 재미가 부담이 되기 때문이에요.', 2),
  (93, 'REASON_PHRASE', 'ANY', '만족도가 ‘룰’에서 결정되기 때문이에요.', 3),
  (94, 'REASON_PHRASE', 'FUNNY', '한도를 넘기면 재미가 부담이 되기 때문이에요. (추천)', 3),
  (95, 'REASON_PHRASE', 'FUNNY', '오늘은 안정감이 관건이기 때문이에요.', 1),
  (96, 'REASON_PHRASE', 'ANY', '작은 성공 경험이 더 오래 가기 때문이에요.', 3),
  (97, 'REASON_PHRASE', 'WARM', '만족도가 ‘룰’에서 결정되기 때문이에요.', 1),
  (98, 'REASON_PHRASE', 'COOL', '작은 성공 경험이 더 오래 가기 때문이에요.', 2),
  (99, 'REASON_PHRASE', 'DRY', '작은 성공 경험이 더 오래 가기 때문이에요.', 4),
  (100, 'REASON_PHRASE', 'WARM', '오늘은 안정감이 관건이기 때문이에요.', 1),
  (101, 'REASON_PHRASE', 'ANY', '한도를 넘기면 재미가 부담이 되기 때문이에요.', 2),
  (102, 'REASON_PHRASE', 'FUNNY', '작은 성공 경험이 더 오래 가기 때문이에요.', 1),
  (103, 'REASON_PHRASE', 'FUNNY', '충동이 올라오면 판단이 흔들리기 때문이에요.', 2),
  (104, 'REASON_PHRASE', 'COOL', '만족도가 ‘룰’에서 결정되기 때문이에요.', 4),
  (105, 'REASON_PHRASE', 'ANY', '한도를 넘기면 재미가 부담이 되기 때문이에요.', 3),
  (106, 'REASON_PHRASE', 'DRY', '작은 성공 경험이 더 오래 가기 때문이에요.', 2),
  (107, 'REASON_PHRASE', 'DRY', '한도를 넘기면 재미가 부담이 되기 때문이에요. 😎', 4),
  (108, 'REASON_PHRASE', 'FUNNY', '작은 성공 경험이 더 오래 가기 때문이에요.', 1),
  (109, 'REASON_PHRASE', 'WARM', '충동이 올라오면 판단이 흔들리기 때문이에요.', 2),
  (110, 'REASON_PHRASE', 'ANY', '한도를 넘기면 재미가 부담이 되기 때문이에요.', 1),
  (111, 'SAFETY_PHRASE', 'ANY', '오늘은 PASS가 더 멋질 수 있어요.', 2),
  (112, 'SAFETY_PHRASE', 'WARM', '한도만 지켜도 오늘은 성공입니다.', 3),
  (113, 'SAFETY_PHRASE', 'ANY', '로또는 재미, 지출은 현실이에요.', 1),
  (114, 'SAFETY_PHRASE', 'DRY', '로또는 재미, 지출은 현실이에요. 😎', 2),
  (115, 'SAFETY_PHRASE', 'ANY', '한도만 지켜도 오늘은 성공입니다.!', 2),
  (116, 'SAFETY_PHRASE', 'FUNNY', '‘더 사기’ 생각이 오면 바로 멈추세요.', 3),
  (117, 'SAFETY_PHRASE', 'COOL', '로또는 재미, 지출은 현실이에요.', 4),
  (118, 'SAFETY_PHRASE', 'DRY', '오늘은 PASS가 더 멋질 수 있어요. 🙂', 2),
  (119, 'SAFETY_PHRASE', 'COOL', '로또는 재미, 지출은 현실이에요. 🙂', 2),
  (120, 'SAFETY_PHRASE', 'DRY', '기분 전환은 다른 걸로도 충분해요.', 4),
  (121, 'SAFETY_PHRASE', 'WARM', '로또는 재미, 지출은 현실이에요.!', 1),
  (122, 'SAFETY_PHRASE', 'ANY', '로또는 재미, 지출은 현실이에요.', 2),
  (123, 'SAFETY_PHRASE', 'WARM', '한도만 지켜도 오늘은 성공입니다. (추천)', 4),
  (124, 'SAFETY_PHRASE', 'ANY', '기분 전환은 다른 걸로도 충분해요. 🙂', 3),
  (125, 'SAFETY_PHRASE', 'DRY', '한도만 지켜도 오늘은 성공입니다.', 4),
  (126, 'SAFETY_PHRASE', 'WARM', '오늘은 PASS가 더 멋질 수 있어요. 🙂', 3),
  (127, 'SAFETY_PHRASE', 'FUNNY', '‘더 사기’ 생각이 오면 바로 멈추세요. 😎', 2),
  (128, 'SAFETY_PHRASE', 'WARM', '기분 전환은 다른 걸로도 충분해요. 😎', 4),
  (129, 'SAFETY_PHRASE', 'DRY', '한도만 지켜도 오늘은 성공입니다.', 2),
  (130, 'SAFETY_PHRASE', 'DRY', '오늘은 PASS가 더 멋질 수 있어요.', 3),
  (131, 'SAFETY_PHRASE', 'DRY', '기분 전환은 다른 걸로도 충분해요.', 4),
  (132, 'SAFETY_PHRASE', 'COOL', '기분 전환은 다른 걸로도 충분해요. 😎', 2),
  (133, 'DO_ACTION', 'WARM', '현금만 챙기고 카드 두고 나가기. 😎', 3),
  (134, 'DO_ACTION', 'COOL', '지출 메모 3줄 쓰기.', 3),
  (135, 'DO_ACTION', 'ANY', '5분 산책하고 결정하기.', 1),
  (136, 'DO_ACTION', 'COOL', '지출 메모 3줄 쓰기.', 2),
  (137, 'DO_ACTION', 'FUNNY', '구매 후 바로 다른 일정으로 이동하기.', 2),
  (138, 'DO_ACTION', 'DRY', '지출 메모 3줄 쓰기.', 1),
  (139, 'DO_ACTION', 'WARM', '구매 후 바로 다른 일정으로 이동하기.', 1),
  (140, 'DO_ACTION', 'ANY', '구매 후 바로 다른 일정으로 이동하기.!', 2),
  (141, 'DO_ACTION', 'WARM', '구매 전 30초만 숨 고르기(10번 호흡). (추천)', 4),
  (142, 'DO_ACTION', 'COOL', '구매 전 30초만 숨 고르기(10번 호흡).', 3),
  (143, 'DO_ACTION', 'WARM', '구매 전 30초만 숨 고르기(10번 호흡).', 3),
  (144, 'DO_ACTION', 'FUNNY', '5분 산책하고 결정하기.', 2),
  (145, 'DO_ACTION', 'ANY', '현금만 챙기고 카드 두고 나가기.', 1),
  (146, 'DO_ACTION', 'COOL', '지출 메모 3줄 쓰기.!', 3),
  (147, 'DO_ACTION', 'FUNNY', '오늘의 한도를 숫자로 적어두기.', 3),
  (148, 'DO_ACTION', 'FUNNY', '오늘의 한도를 숫자로 적어두기. 😎', 3),
  (149, 'DO_ACTION', 'WARM', '오늘의 한도를 숫자로 적어두기.', 1),
  (150, 'DO_ACTION', 'COOL', '5분 산책하고 결정하기.', 4),
  (151, 'DO_ACTION', 'COOL', '현금만 챙기고 카드 두고 나가기.', 4),
  (152, 'DO_ACTION', 'DRY', '현금만 챙기고 카드 두고 나가기.', 2),
  (153, 'DO_ACTION', 'DRY', '오늘의 한도를 숫자로 적어두기. 🙂', 4),
  (154, 'DO_ACTION', 'ANY', '오늘의 한도를 숫자로 적어두기.', 2),
  (155, 'FUN_MISSION_TEXT', 'COOL', '물 한 컵 마시기.', 1),
  (156, 'FUN_MISSION_TEXT', 'ANY', '하늘 사진 한 장 찍기.', 1),
  (157, 'FUN_MISSION_TEXT', 'ANY', '친구에게 응원 메시지 보내기.', 4),
  (158, 'FUN_MISSION_TEXT', 'COOL', '편의점에서 가장 작은 행운 간식 고르기.', 2),
  (159, 'FUN_MISSION_TEXT', 'FUNNY', '친구에게 응원 메시지 보내기. 🙂', 4),
  (160, 'FUN_MISSION_TEXT', 'COOL', '친구에게 응원 메시지 보내기. 🙂', 3),
  (161, 'FUN_MISSION_TEXT', 'COOL', '책상 위 1분 정리하기.', 3),
  (162, 'FUN_MISSION_TEXT', 'WARM', '책상 위 1분 정리하기.!', 3),
  (163, 'FUN_MISSION_TEXT', 'DRY', '하늘 사진 한 장 찍기.', 1),
  (164, 'FUN_MISSION_TEXT', 'WARM', '책상 위 1분 정리하기.', 4),
  (165, 'FUN_MISSION_TEXT', 'ANY', '물 한 컵 마시기.', 1),
  (166, 'FUN_MISSION_TEXT', 'WARM', '편의점에서 가장 작은 행운 간식 고르기. 😎', 1),
  (167, 'FUN_MISSION_TEXT', 'DRY', '친구에게 응원 메시지 보내기.', 3),
  (168, 'FUN_MISSION_TEXT', 'DRY', '물 한 컵 마시기.', 3),
  (169, 'FUN_MISSION_TEXT', 'WARM', '하늘 사진 한 장 찍기.', 4),
  (170, 'FUN_MISSION_TEXT', 'WARM', '책상 위 1분 정리하기.', 3),
  (171, 'FUN_MISSION_TEXT', 'DRY', '좋아하는 노래 1곡 듣기.', 2),
  (172, 'FUN_MISSION_TEXT', 'COOL', '물 한 컵 마시기. 🙂', 2),
  (173, 'FUN_MISSION_TEXT', 'DRY', '하늘 사진 한 장 찍기.', 1),
  (174, 'FUN_MISSION_TEXT', 'DRY', '하늘 사진 한 장 찍기.', 1),
  (175, 'FUN_MISSION_TEXT', 'WARM', '편의점에서 가장 작은 행운 간식 고르기. (추천)', 1),
  (176, 'FUN_MISSION_TEXT', 'DRY', '좋아하는 노래 1곡 듣기.!', 1),
  (177, 'INTENSITY_WORD', 'DRY', '소액 도전 😎', 1),
  (178, 'INTENSITY_WORD', 'WARM', '오늘은 절제', 3),
  (179, 'INTENSITY_WORD', 'FUNNY', '가볍게 1~2장', 2),
  (180, 'INTENSITY_WORD', 'ANY', '한 장만', 3),
  (181, 'INTENSITY_WORD', 'FUNNY', '한 장만 😎', 4),
  (182, 'INTENSITY_WORD', 'FUNNY', 'PASS(쉬는 게 이득)', 2),
  (183, 'INTENSITY_WORD', 'COOL', '조심스럽게 😎', 3),
  (184, 'INTENSITY_WORD', 'COOL', '도전 OK(한도 내)', 1),
  (185, 'INTENSITY_WORD', 'ANY', '오늘은 절제 😎', 2),
  (186, 'INTENSITY_WORD', 'ANY', '소액 도전 😎', 2),
  (187, 'INTENSITY_WORD', 'FUNNY', '조심스럽게 🙂', 2),
  (188, 'INTENSITY_WORD', 'DRY', '도전 OK(한도 내)!', 2),
  (189, 'INTENSITY_WORD', 'FUNNY', 'PASS(쉬는 게 이득)', 4),
  (190, 'INTENSITY_WORD', 'FUNNY', '쿨하게 PASS', 2),
  (191, 'INTENSITY_WORD', 'FUNNY', '조심스럽게 (추천)', 1),
  (192, 'INTENSITY_WORD', 'DRY', '한 장만', 3),
  (193, 'INTENSITY_WORD', 'WARM', '조심스럽게 (추천)', 3),
  (194, 'INTENSITY_WORD', 'COOL', '소액 도전!', 3),
  (195, 'INTENSITY_WORD', 'ANY', '딱 1회만', 3),
  (196, 'INTENSITY_WORD', 'ANY', '오늘은 절제 😎', 2),
  (197, 'INTENSITY_WORD', 'FUNNY', '딱 1회만', 1),
  (198, 'INTENSITY_WORD', 'FUNNY', '조심스럽게!', 1),
  (199, 'TIME_WINDOW', 'ANY', '집 가는 길에만!', 1),
  (200, 'BUDGET_SMALL', 'COOL', '오늘은 최소!', 3);
