-- V3__seed_questions.sql
INSERT INTO question (bucket,text,primary_axis,secondary_axis,strength,polarity,tag_on_high,tag_on_low,weight) VALUES
  ('OPTIMISM','오늘은 괜히 좋은 일이 생길 것 같은 기분이다 (그냥 느낌이다)','OPTIMISM',NULL,1.0,1,'LUCKY_VIBE','ADVENTURE_MODE',2),
  ('OPTIMISM','오늘은 괜히 불길한 예감이 든다 (살짝 과장일 수도)','OPTIMISM','ENERGY',1.2,-1,'BOLD_MOVE','IMPULSE_BUY',1),
  ('OPTIMISM','기분이 축 처져서 도전 생각이 안 든다 (그냥 느낌이다)','OPTIMISM',NULL,0.8,-1,'FOCUS_ON','UNSTABLE_MIND',3),
  ('OPTIMISM','뭔가 꼬일 것 같은 느낌이 있다 (근거는 없다)','OPTIMISM','IMPULSIVITY',1.2,-1,'PLAN_OK','BOLD_MOVE',1),
  ('OPTIMISM','대화가 술술 풀리고 웃을 일이 있다 (근거는 없다)','OPTIMISM','RISK',1.2,1,'ADVENTURE_MODE','STRESS_HIGH',2),
  ('OPTIMISM','오늘은 괜히 불길한 예감이 든다 (요즘 자주 그렇다)','OPTIMISM',NULL,0.8,-1,'LUCKY_VIBE','TASK_DONE',2),
  ('OPTIMISM','작은 행운 신호(우연, 우스운 일치)를 자주 본다 (오늘 특히 그렇다)','OPTIMISM','ENERGY',1.4,1,'DISTRACTED','ENERGY_LOW_TAG',3),
  ('OPTIMISM','희망 회로가 잘 안 돌아간다 (평소보다 더)','OPTIMISM','ENERGY',1.4,-1,'BODY_LIGHT','PLAN_OK',3),
  ('OPTIMISM','작은 일에도 의심이 먼저 생긴다 (근거는 없다)','OPTIMISM','FIN_EASE',0.8,-1,'MIND_FOG','BOLD_MOVE',1),
  ('OPTIMISM','오늘은 새 출발을 해도 될 것 같다 (평소보다 더)','OPTIMISM','ENERGY',1.3,1,'GUILTY_SPEND','PATIENT',3),
  ('OPTIMISM','오늘은 새 출발을 해도 될 것 같다 (그냥 느낌이다)','OPTIMISM',NULL,1.1,1,'LUCKY_VIBE','CLEAR_HEAD',3),
  ('OPTIMISM','대화가 술술 풀리고 웃을 일이 있다 (내 기분 기준)','OPTIMISM','RISK',1.3,1,'PLAN_OK','HOPEFUL',3),
  ('OPTIMISM','주변 분위기가 밝게 느껴진다 (그냥 느낌이다)','OPTIMISM','FIN_EASE',1.0,1,'MIND_FOG','UNSTABLE_MIND',1),
  ('OPTIMISM','오늘은 새 출발을 해도 될 것 같다 (내 기분 기준)','OPTIMISM','IMPULSIVITY',1.4,1,'SELF_CONTROL','ENERGY_HIGH_TAG',2),
  ('OPTIMISM','오늘은 새 출발을 해도 될 것 같다 (살짝 과장일 수도)','OPTIMISM',NULL,1.1,1,'PROCRASTINATE','SOCIAL_DRAIN',3),
  ('OPTIMISM','사소한 실패도 ‘괜찮아’ 하고 넘길 수 있다 (요즘 자주 그렇다)','OPTIMISM',NULL,1.1,1,'LUCKY_VIBE','SELF_CONTROL',1),
  ('OPTIMISM','뭔가 꼬일 것 같은 느낌이 있다 (근거는 없다)','OPTIMISM','IMPULSIVITY',0.9,-1,'SOCIAL_GOOD','PLAN_OK',1),
  ('OPTIMISM','주변 분위기가 밝게 느껴진다 (평소보다 더)','OPTIMISM',NULL,0.9,1,'MONEY_TIGHT','COFFEE_NEED',3),
  ('OPTIMISM','뭔가 꼬일 것 같은 느낌이 있다 (살짝 과장일 수도)','OPTIMISM',NULL,1.3,-1,'PESSIMISTIC','PESSIMISTIC',2),
  ('OPTIMISM','평소보다 마음이 가벼워서 ‘한 번 해볼까?’가 쉽게 나온다 (그냥 느낌이다)','OPTIMISM',NULL,0.8,1,'STRESS_LOW','BODY_LIGHT',1),
  ('STABILITY','감정이 오락가락해서 집중이 안 된다 (근거는 없다)','STABILITY','OPTIMISM',0.8,-1,'TASK_DONE','ADVENTURE_MODE',2),
  ('STABILITY','계획대로 움직이는 게 편하다 (오늘 특히 그렇다)','STABILITY','IMPULSIVITY',1.2,1,'PATIENT','STABILITY_LOW',2),
  ('STABILITY','정리정돈/루틴이 잘 지켜진다 (내 기분 기준)','STABILITY','FIN_EASE',0.8,1,'CLEAR_HEAD','PLAN_CHAOS',1),
  ('STABILITY','정리정돈/루틴이 잘 지켜진다 (근거는 없다)','STABILITY','RISK',0.9,1,'SLEEPY','DOUBT_CLOUD',1),
  ('STABILITY','작업 흐름이 안정적으로 이어진다 (오늘 특히 그렇다)','STABILITY','ENERGY',1.2,1,'SELF_CONTROL','SOCIAL_GOOD',3),
  ('STABILITY','계획대로 움직이는 게 편하다 (평소보다 더)','STABILITY',NULL,1.0,1,'FOCUS_ON','STRESS_HIGH',1),
  ('STABILITY','계획대로 움직이는 게 편하다 (내 기분 기준)','STABILITY',NULL,1.4,1,'PATIENT','STABILITY_LOW',1),
  ('STABILITY','감정이 오락가락해서 집중이 안 된다 (평소보다 더)','STABILITY','RISK',1.4,-1,'BODY_LIGHT','PATIENT',2),
  ('STABILITY','갑작스러운 변수에도 크게 흔들리지 않는다 (요즘 자주 그렇다)','STABILITY','IMPULSIVITY',0.8,1,'CLEAR_HEAD','LUCKY_VIBE',2),
  ('STABILITY','오늘은 마음이 차분하고 평정심이 유지된다 (살짝 과장일 수도)','STABILITY','OPTIMISM',1.3,1,'STRESS_HIGH','CLEAR_HEAD',1),
  ('STABILITY','한 가지에 오래 못 붙어 있는 느낌이다 (살짝 과장일 수도)','STABILITY',NULL,1.1,-1,'BODY_HEAVY','PESSIMISTIC',3),
  ('STABILITY','머릿속이 복잡해서 결정을 미루고 싶다','STABILITY',NULL,0.8,-1,'MONEY_EASY','STABILITY_LOW',3),
  ('STABILITY','정리정돈/루틴이 잘 지켜진다 (평소보다 더)','STABILITY',NULL,0.9,1,'MONEY_EASY','PROCRASTINATE',3),
  ('STABILITY','계획대로 움직이는 게 편하다 (살짝 과장일 수도)','STABILITY','OPTIMISM',0.9,1,'STRESS_HIGH','STRESS_LOW',1),
  ('STABILITY','감정이 오락가락해서 집중이 안 된다 (평소보다 더)','STABILITY','ENERGY',1.0,-1,'SOCIAL_GOOD','TASK_DONE',2),
  ('STABILITY','감정 기복이 적고 균형감이 있다 (살짝 과장일 수도)','STABILITY','RISK',1.4,1,'COFFEE_NEED','MONEY_TIGHT',3),
  ('STABILITY','루틴이 자꾸 깨지고 산만해진다 (근거는 없다)','STABILITY',NULL,0.9,-1,'LUCKY_VIBE','STABILITY_LOW',1),
  ('STABILITY','결정할 때 급하지 않고 천천히 생각한다','STABILITY',NULL,0.9,1,'SMALL_REWARD','SLEEPY',3),
  ('STABILITY','결정할 때 급하지 않고 천천히 생각한다','STABILITY',NULL,1.2,1,'DISTRACTED','STRESS_HIGH',2),
  ('STABILITY','결정할 때 급하지 않고 천천히 생각한다','STABILITY',NULL,0.8,1,'IMPULSE_BUY','BODY_LIGHT',2),
  ('IMPULSIVITY','할인/이벤트를 보면 손이 먼저 간다 (오늘 특히 그렇다)','IMPULSIVITY',NULL,1.2,1,'BODY_LIGHT','COFFEE_NEED',3),
  ('IMPULSIVITY','즉흥적으로 약속이나 계획을 잡고 싶다 (오늘 특히 그렇다)','IMPULSIVITY',NULL,1.4,1,'PROCRASTINATE','STRESS_HIGH',2),
  ('IMPULSIVITY','생각보다 행동이 앞선다 (그냥 느낌이다)','IMPULSIVITY',NULL,0.9,1,'IMPULSE_BUY','SAFE_PLAY',1),
  ('IMPULSIVITY','참고 있던 걸 확 질러버리고 싶다 (근거는 없다)','IMPULSIVITY',NULL,0.9,1,'RUSHING','MONEY_EASY',2),
  ('IMPULSIVITY','오늘은 충동을 잘 참을 수 있다 (살짝 과장일 수도)','IMPULSIVITY',NULL,0.9,-1,'MIND_FOG','ENERGY_HIGH_TAG',3),
  ('IMPULSIVITY','기분 전환 소비를 하고 싶다 (평소보다 더)','IMPULSIVITY','FIN_EASE',1.4,1,'BOLD_MOVE','STRESS_HIGH',2),
  ('IMPULSIVITY','‘나중에’가 더 편하다 (내 기분 기준)','IMPULSIVITY','RISK',1.0,-1,'BODY_LIGHT','DOUBT_CLOUD',2),
  ('IMPULSIVITY','오늘은 충동을 잘 참을 수 있다 (그냥 느낌이다)','IMPULSIVITY',NULL,1.0,-1,'IMPULSE_BUY','ADVENTURE_MODE',1),
  ('IMPULSIVITY','계획 없는 소비는 피하고 싶다 (살짝 과장일 수도)','IMPULSIVITY','STABILITY',1.0,-1,'SOCIAL_GOOD','PESSIMISTIC',1),
  ('IMPULSIVITY','즉흥적으로 약속이나 계획을 잡고 싶다 (평소보다 더)','IMPULSIVITY',NULL,1.2,1,'SELF_CONTROL','SOCIAL_DRAIN',1);

INSERT INTO question (bucket,text,primary_axis,secondary_axis,strength,polarity,tag_on_high,tag_on_low,weight) VALUES
  ('IMPULSIVITY','오늘은 ‘지금 당장!’이 자주 튀어나온다 (오늘 특히 그렇다)','IMPULSIVITY',NULL,1.4,1,'DOUBT_CLOUD','SELF_CONTROL',2),
  ('IMPULSIVITY','결정 전에 한 번 더 생각한다 (그냥 느낌이다)','IMPULSIVITY',NULL,0.8,-1,'BODY_HEAVY','LUCKY_VIBE',2),
  ('IMPULSIVITY','한 번 시작하면 멈추기 어렵다 (근거는 없다)','IMPULSIVITY',NULL,1.2,1,'IMPULSE_BUY','SLEEPY',3),
  ('IMPULSIVITY','생각보다 행동이 앞선다','IMPULSIVITY',NULL,0.9,1,'ENERGY_LOW_TAG','STRESS_HIGH',2),
  ('IMPULSIVITY','‘나중에’가 더 편하다 (근거는 없다)','IMPULSIVITY','STABILITY',1.3,-1,'SOCIAL_DRAIN','PATIENT',1),
  ('IMPULSIVITY','한 번 시작하면 멈추기 어렵다 (요즘 자주 그렇다)','IMPULSIVITY','OPTIMISM',1.0,1,'COFFEE_NEED','CLEAR_HEAD',1),
  ('IMPULSIVITY','한 번 시작하면 멈추기 어렵다 (살짝 과장일 수도)','IMPULSIVITY','FIN_EASE',1.1,1,'COFFEE_NEED','PLAN_CHAOS',3),
  ('IMPULSIVITY','즉흥 구매보다 계획을 우선한다 (근거는 없다)','IMPULSIVITY',NULL,0.9,-1,'IMPULSE_BUY','PATIENT',1),
  ('IMPULSIVITY','생각보다 행동이 앞선다 (살짝 과장일 수도)','IMPULSIVITY','OPTIMISM',1.4,1,'ENERGY_HIGH_TAG','UNSTABLE_MIND',1),
  ('IMPULSIVITY','즉흥적으로 약속이나 계획을 잡고 싶다 (오늘 특히 그렇다)','IMPULSIVITY',NULL,1.3,1,'DISTRACTED','PLAN_OK',1),
  ('RISK','확률 게임도 재미로 받아들일 수 있다 (평소보다 더)','RISK','IMPULSIVITY',1.1,1,'GUILTY_SPEND','PROCRASTINATE',2),
  ('RISK','불확실한 일은 피하고 싶다','RISK','IMPULSIVITY',0.9,-1,'GUILTY_SPEND','HOPEFUL',1),
  ('RISK','안정적인 루트가 더 낫다','RISK','STABILITY',1.1,-1,'SELF_CONTROL','SOCIAL_GOOD',1),
  ('RISK','확률 게임도 재미로 받아들일 수 있다 (오늘 특히 그렇다)','RISK','OPTIMISM',0.9,1,'FOCUS_ON','SELF_CONTROL',3),
  ('RISK','결과가 예측되지 않으면 불안하다 (살짝 과장일 수도)','RISK',NULL,1.2,-1,'SMALL_REWARD','MIND_FOG',1),
  ('RISK','오늘은 새로운 선택이 흥미롭다 (살짝 과장일 수도)','RISK',NULL,1.0,1,'COFFEE_NEED','MONEY_TIGHT',3),
  ('RISK','안전빵보다 변주가 좋다','RISK',NULL,1.4,1,'FOCUS_ON','SELF_CONTROL',1),
  ('RISK','남들이 안 하는 걸 해보고 싶다 (내 기분 기준)','RISK','IMPULSIVITY',0.8,1,'PROCRASTINATE','UNSTABLE_MIND',3),
  ('RISK','남들이 안 하는 걸 해보고 싶다 (오늘 특히 그렇다)','RISK',NULL,0.8,1,'LUCKY_VIBE','BODY_HEAVY',1),
  ('RISK','오늘은 새로운 선택이 흥미롭다 (그냥 느낌이다)','RISK',NULL,1.3,1,'CLEAR_HEAD','SOCIAL_GOOD',1),
  ('RISK','결과가 예측되지 않으면 불안하다 (내 기분 기준)','RISK','STABILITY',1.4,-1,'MIND_FOG','HOPEFUL',1),
  ('RISK','오늘은 안전한 선택이 더 끌린다 (요즘 자주 그렇다)','RISK',NULL,1.1,-1,'IMPULSE_BUY','MONEY_EASY',2),
  ('RISK','도전이 스트레스 해소가 된다 (근거는 없다)','RISK',NULL,1.0,1,'LUCKY_VIBE','CLEAR_HEAD',1),
  ('RISK','한 번쯤 ‘질러보는’ 선택이 끌린다 (내 기분 기준)','RISK','OPTIMISM',1.1,1,'PLAN_OK','SLEEPY',2),
  ('RISK','도전이 스트레스 해소가 된다 (요즘 자주 그렇다)','RISK',NULL,1.1,1,'PLAN_CHAOS','SELF_CONTROL',2),
  ('RISK','남들이 안 하는 걸 해보고 싶다 (오늘 특히 그렇다)','RISK','OPTIMISM',0.8,1,'HOPEFUL','STRESS_LOW',1),
  ('RISK','조심스러운 편이 편안하다 (오늘 특히 그렇다)','RISK',NULL,0.8,-1,'RUSHING','MONEY_TIGHT',3),
  ('RISK','오늘은 안전한 선택이 더 끌린다 (평소보다 더)','RISK',NULL,1.4,-1,'FOCUS_ON','MIND_FOG',2),
  ('RISK','한 번쯤 ‘질러보는’ 선택이 끌린다 (내 기분 기준)','RISK','OPTIMISM',1.1,1,'PESSIMISTIC','PLAN_CHAOS',3),
  ('RISK','오늘은 새로운 선택이 흥미롭다 (평소보다 더)','RISK',NULL,0.9,1,'LUCKY_VIBE','SMALL_REWARD',2),
  ('MIX','수면이 괜찮아서 판단이 또렷하다 (오늘 특히 그렇다)','STABILITY','IMPULSIVITY',1.4,1,'SOCIAL_GOOD','RUSHING',1),
  ('MIX','스트레스가 낮아서 결정을 담백하게 한다 (살짝 과장일 수도)','STABILITY',NULL,1.1,1,'SOCIAL_DRAIN','UNSTABLE_MIND',2),
  ('MIX','컨디션이 좋아서 뭐든 가볍게 즐길 수 있다 (요즘 자주 그렇다)','FIN_EASE','IMPULSIVITY',0.8,1,'STRESS_HIGH','SAFE_PLAY',3),
  ('MIX','기분이 안정되어 지출을 통제할 수 있다 (살짝 과장일 수도)','ENERGY','RISK',1.0,1,'MONEY_TIGHT','PROCRASTINATE',1),
  ('MIX','기분이 안정되어 지출을 통제할 수 있다 (근거는 없다)','FIN_EASE','RISK',1.3,1,'PLAN_OK','MIND_FOG',1),
  ('MIX','스트레스가 높아 무언가로 풀고 싶다 (오늘 특히 그렇다)','ENERGY','RISK',1.2,-1,'SOCIAL_GOOD','PESSIMISTIC',3),
  ('MIX','과로 느낌이 있어 판단이 흔들린다 (근거는 없다)','OPTIMISM','FIN_EASE',0.9,-1,'IMPULSE_BUY','STRESS_LOW',3),
  ('MIX','기분이 안정되어 지출을 통제할 수 있다 (내 기분 기준)','STABILITY','FIN_EASE',1.4,1,'STRESS_HIGH','MONEY_TIGHT',3),
  ('MIX','스트레스가 낮아서 결정을 담백하게 한다 (요즘 자주 그렇다)','ENERGY','IMPULSIVITY',0.9,1,'MONEY_TIGHT','SOCIAL_GOOD',3),
  ('MIX','수면이 괜찮아서 판단이 또렷하다 (요즘 자주 그렇다)','FIN_EASE','RISK',0.9,1,'HOPEFUL','SOCIAL_DRAIN',2),
  ('MIX','컨디션이 좋아서 뭐든 가볍게 즐길 수 있다 (요즘 자주 그렇다)','FIN_EASE','ENERGY',1.4,1,'SELF_CONTROL','SOCIAL_DRAIN',1),
  ('MIX','기분이 안정되어 지출을 통제할 수 있다','STABILITY','FIN_EASE',1.1,1,'MONEY_TIGHT','CALM_MIND',2),
  ('MIX','오늘은 지갑 사정이 비교적 여유롭다 (살짝 과장일 수도)','STABILITY',NULL,1.3,1,'STRESS_HIGH','BODY_HEAVY',2),
  ('MIX','수면이 괜찮아서 판단이 또렷하다 (그냥 느낌이다)','FIN_EASE','STABILITY',0.9,1,'MONEY_TIGHT','SELF_CONTROL',3),
  ('MIX','오늘은 지출이 부담으로 느껴진다 (오늘 특히 그렇다)','FIN_EASE','STABILITY',1.4,-1,'MONEY_TIGHT','SOCIAL_GOOD',3),
  ('MIX','스트레스가 높아 무언가로 풀고 싶다 (요즘 자주 그렇다)','STABILITY','OPTIMISM',1.3,-1,'HOPEFUL','SOCIAL_GOOD',1),
  ('MIX','지갑이 타이트해서 신중해진다 (오늘 특히 그렇다)','RISK','ENERGY',1.4,-1,'SMALL_REWARD','DISTRACTED',2),
  ('MIX','수면이 괜찮아서 판단이 또렷하다 (오늘 특히 그렇다)','ENERGY','OPTIMISM',1.2,1,'UNSTABLE_MIND','DOUBT_CLOUD',1),
  ('MIX','과로 느낌이 있어 판단이 흔들린다 (살짝 과장일 수도)','IMPULSIVITY','OPTIMISM',1.1,-1,'RUSHING','FOCUS_ON',2),
  ('MIX','작은 보상(커피/간식) 정도는 부담 없다 (요즘 자주 그렇다)','IMPULSIVITY','FIN_EASE',0.8,1,'LUCKY_VIBE','PLAN_OK',3);
