-- V5__seed_message_pool.sql
INSERT INTO message_pool (id, category, tone, min_score, max_score, required_tags, blocked_tags, conditions_json, text, weight, priority) VALUES
  (1, 'INSIGHT', 'COOL', 55, 60, 'MONEY_TIGHT', NULL, NULL, '오늘은 재미는 OK, 과금은 NO.', 3, 0),
  (2, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '오늘은 소액이 더 어울려요. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 1, 0),
  (3, 'INSIGHT', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘은 가벼운 즐김이 적당해요. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 3, 3),
  (4, 'INSIGHT', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘은 재미는 OK, 과금은 NO.', 1, 3),
  (5, 'INSIGHT', 'COOL', 0, 100, NULL, NULL, NULL, '충동 버튼이 살짝 민감 신호가 보여요. 잠깐 산책하고 결정해요', 1, 1),
  (6, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '룰만 지키면 만족도가 올라가요.', 3, 1),
  (7, 'INSIGHT', 'COOL', 0, 100, NULL, NULL, NULL, '기분이 가벼운 편라서 오늘은 오늘 한도 고정가 특히 중요해요.', 1, 2),
  (8, 'INSIGHT', 'ANY', 0, 100, NULL, NULL, NULL, '오늘은 여유가 있어도 과장은 금지. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 3, 0),
  (9, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '오늘은 재미는 OK, 과금은 NO.', 1, 3),
  (10, 'INSIGHT', 'WARM', 0, 100, NULL, NULL, NULL, '오늘은 무리하면 후회가 커요. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 1, 3),
  (11, 'INSIGHT', 'DRY', 55, 100, 'LUCKY_VIBE', NULL, NULL, '룰만 지키면 만족도가 올라가요.', 3, 3),
  (12, 'INSIGHT', 'COOL', 0, 60, 'MONEY_TIGHT', NULL, NULL, '충동 버튼이 살짝 민감 신호가 보여요. ‘한 장’으로 마무리해요', 2, 2),
  (13, 'INSIGHT', 'WARM', 0, 100, NULL, NULL, NULL, '조금 예민한 편라서 오늘은 현금만 룰가 특히 중요해요.', 3, 1),
  (14, 'INSIGHT', 'FUNNY', 0, 100, NULL, NULL, NULL, '초반에 분위기가 과열될 수 있는 날라 친구에게 선언을 걸어두면 안정적이에요.', 2, 1),
  (15, 'INSIGHT', 'COOL', 0, 100, NULL, NULL, NULL, 'PASS도 훌륭한 선택이에요.', 2, 1),
  (16, 'INSIGHT', 'ANY', 0, 100, NULL, NULL, NULL, '평정이 안정적인 편라서 오늘은 ‘더 사기’ 금지가 특히 중요해요.', 1, 2),
  (17, 'INSIGHT', 'ANY', 0, 100, NULL, NULL, NULL, '오늘은 재미는 OK, 과금은 NO.', 2, 3),
  (18, 'INSIGHT', 'FUNNY', 0, 100, NULL, NULL, NULL, '충동 버튼이 살짝 민감 신호가 보여요. 잠깐 산책하고 결정해요', 3, 3),
  (19, 'INSIGHT', 'ANY', 0, 100, NULL, NULL, NULL, '조금 예민한 편라서 오늘은 ‘더 사기’ 금지가 특히 중요해요.', 3, 1),
  (20, 'INSIGHT', 'WARM', 0, 100, NULL, NULL, NULL, '기분이 가벼운 편라서 오늘은 1장 룰가 특히 중요해요.', 2, 1),
  (21, 'INSIGHT', 'COOL', 55, 100, 'LUCKY_VIBE', NULL, NULL, '충동 버튼이 살짝 민감 신호가 보여요. 오늘은 공유하고 끝내요', 1, 0),
  (22, 'INSIGHT', 'COOL', 0, 100, NULL, NULL, NULL, '평정이 안정적인 편라서 오늘은 ‘더 사기’ 금지가 특히 중요해요.', 1, 0),
  (23, 'INSIGHT', 'DRY', 0, 60, 'MONEY_TIGHT', NULL, NULL, '컨디션이 들쑥날쑥라서 오늘은 오늘 한도 고정가 특히 중요해요.', 2, 0),
  (24, 'INSIGHT', 'COOL', 0, 100, NULL, NULL, NULL, '오늘은 한도를 낮게 잡는 게 안전해요. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 2, 1),
  (25, 'INSIGHT', 'WARM', 0, 100, NULL, NULL, NULL, '머리가 맑은 편라서 오늘은 1장 룰가 특히 중요해요.', 3, 0),
  (26, 'INSIGHT', 'COOL', 0, 100, NULL, NULL, NULL, '오늘은 여유가 있어도 과장은 금지. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 1, 3),
  (27, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '안정감이 떨어지기 쉬운 날라 친구에게 선언을 걸어두면 안정적이에요.', 3, 1),
  (28, 'INSIGHT', 'FUNNY', 0, 100, NULL, NULL, NULL, '시작은 쉬운데 멈춤이 어려울 수 있는 날라 딱 1회 방문을 걸어두면 안정적이에요.', 1, 0),
  (29, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '기분이 좋을수록 규칙이 필요해요.', 2, 1),
  (30, 'INSIGHT', 'FUNNY', 0, 100, NULL, NULL, NULL, '룰만 지키면 만족도가 올라가요.', 1, 2),
  (31, 'INSIGHT', 'COOL', 55, 100, 'LUCKY_VIBE', NULL, NULL, '오늘은 소액이 더 어울려요. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 3, 2),
  (32, 'INSIGHT', 'WARM', 0, 100, NULL, NULL, NULL, '안정감이 떨어지기 쉬운 날라 구매 후 바로 집 가기을 걸어두면 안정적이에요.', 1, 0),
  (33, 'INSIGHT', 'ANY', 0, 100, NULL, NULL, NULL, '평정이 안정적인 편라서 오늘은 오늘 한도 고정가 특히 중요해요.', 2, 1),
  (34, 'INSIGHT', 'FUNNY', 0, 60, 'MONEY_TIGHT', NULL, NULL, '머리가 맑은 편라서 오늘은 1장 룰가 특히 중요해요.', 3, 3),
  (35, 'INSIGHT', 'COOL', 0, 100, NULL, NULL, NULL, '오늘은 가벼운 즐김이 적당해요. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 2, 3),
  (36, 'INSIGHT', 'ANY', 0, 100, NULL, NULL, NULL, '안정감이 떨어지기 쉬운 날라 딱 1회 방문을 걸어두면 안정적이에요.', 2, 3),
  (37, 'INSIGHT', 'FUNNY', 0, 100, NULL, NULL, NULL, '안정감이 떨어지기 쉬운 날라 친구에게 선언을 걸어두면 안정적이에요.', 1, 2),
  (38, 'INSIGHT', 'ANY', 0, 100, NULL, NULL, NULL, '기분이 가벼운 편라서 오늘은 ‘더 사기’ 금지가 특히 중요해요.', 2, 1),
  (39, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '룰만 지키면 만족도가 올라가요.', 1, 0),
  (40, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '재정 신호가 타이트 신호가 보여요. 구매 전 목표를 한 문장으로 적어봐요', 1, 1),
  (41, 'INSIGHT', 'ANY', 55, 100, 'LUCKY_VIBE', NULL, NULL, '기분이 가벼운 편라서 오늘은 구매 전 10초 멈춤가 특히 중요해요.', 3, 2),
  (42, 'INSIGHT', 'WARM', 0, 100, NULL, NULL, NULL, '오늘은 소액이 더 어울려요. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 2, 2),
  (43, 'INSIGHT', 'COOL', 0, 100, NULL, NULL, NULL, '오늘은 무리하면 후회가 커요. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 1, 1),
  (44, 'INSIGHT', 'ANY', 0, 100, NULL, NULL, NULL, '초반에 분위기가 과열될 수 있는 날라 친구에게 선언을 걸어두면 안정적이에요.', 2, 3),
  (45, 'INSIGHT', 'WARM', 0, 60, 'MONEY_TIGHT', NULL, NULL, '도전 욕구가 올라옴 신호가 보여요. 현금만 들고 나가봐요', 2, 0),
  (46, 'INSIGHT', 'WARM', 0, 100, NULL, NULL, NULL, '‘한도’가 당신의 행운템입니다.', 3, 0),
  (47, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '시작은 쉬운데 멈춤이 어려울 수 있는 날라 딱 1회 방문을 걸어두면 안정적이에요.', 2, 1),
  (48, 'INSIGHT', 'ANY', 0, 100, NULL, NULL, NULL, '‘한도’가 당신의 행운템입니다.', 2, 2),
  (49, 'INSIGHT', 'ANY', 0, 100, NULL, NULL, NULL, '오늘은 무리하면 후회가 커요. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 3, 3),
  (50, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '안정감이 떨어지기 쉬운 날라 친구에게 선언을 걸어두면 안정적이에요.', 2, 3),
  (51, 'INSIGHT', 'DRY', 55, 100, 'LUCKY_VIBE', NULL, NULL, '오늘은 재미는 OK, 과금은 NO.', 2, 2),
  (52, 'INSIGHT', 'COOL', 0, 100, NULL, NULL, NULL, '오늘은 재미는 OK, 과금은 NO.', 2, 0),
  (53, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '재정 신호가 타이트 신호가 보여요. 구매 전 목표를 한 문장으로 적어봐요', 1, 1),
  (54, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '안정감이 떨어질 수 있음 신호가 보여요. ‘한 장’으로 마무리해요', 1, 3),
  (55, 'INSIGHT', 'ANY', 0, 100, NULL, NULL, NULL, '오늘은 소액이 더 어울려요. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 1, 2),
  (56, 'INSIGHT', 'COOL', 0, 60, 'MONEY_TIGHT', NULL, NULL, '충동 버튼이 살짝 민감 신호가 보여요. 오늘은 공유하고 끝내요', 3, 3),
  (57, 'INSIGHT', 'FUNNY', 0, 100, NULL, NULL, NULL, '컨디션이 좋아 보임 신호가 보여요. 오늘은 공유하고 끝내요', 1, 3),
  (58, 'INSIGHT', 'COOL', 0, 100, NULL, NULL, NULL, '도전 욕구가 올라옴 신호가 보여요. ‘한 장’으로 마무리해요', 1, 2),
  (59, 'INSIGHT', 'ANY', 0, 100, NULL, NULL, NULL, '계획대로 가면 편한 날라 구매 후 바로 집 가기을 걸어두면 안정적이에요.', 1, 1),
  (60, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '시작은 쉬운데 멈춤이 어려울 수 있는 날라 지갑 닫기 알림을 걸어두면 안정적이에요.', 2, 0),
  (61, 'INSIGHT', 'ANY', 55, 100, 'LUCKY_VIBE', NULL, NULL, '‘한도’가 당신의 행운템입니다.', 2, 0),
  (62, 'INSIGHT', 'WARM', 0, 100, NULL, NULL, NULL, '오늘은 재미는 OK, 과금은 NO.', 2, 0),
  (63, 'INSIGHT', 'COOL', 0, 100, NULL, NULL, NULL, '계획대로 가면 편한 날라 ‘1번만’ 규칙을 걸어두면 안정적이에요.', 2, 1),
  (64, 'INSIGHT', 'WARM', 0, 100, NULL, NULL, NULL, '오늘은 가벼운 즐김이 적당해요. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 2, 0),
  (65, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '룰만 지키면 만족도가 올라가요.', 2, 0),
  (66, 'INSIGHT', 'ANY', 0, 100, NULL, NULL, NULL, '즉흥성이 올라오기 쉬운 날라 구매 후 바로 집 가기을 걸어두면 안정적이에요.', 1, 2),
  (67, 'INSIGHT', 'ANY', 0, 60, 'MONEY_TIGHT', NULL, NULL, '오늘은 소액이 더 어울려요. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 3, 3),
  (68, 'INSIGHT', 'ANY', 0, 100, NULL, NULL, NULL, '안정감이 떨어지기 쉬운 날라 지갑 닫기 알림을 걸어두면 안정적이에요.', 1, 2),
  (69, 'INSIGHT', 'ANY', 0, 100, NULL, NULL, NULL, '오늘은 소액이 더 어울려요. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 3, 0),
  (70, 'INSIGHT', 'COOL', 0, 100, NULL, NULL, NULL, '안정감이 떨어지기 쉬운 날라 친구에게 선언을 걸어두면 안정적이에요.', 1, 1),
  (71, 'INSIGHT', 'WARM', 55, 100, 'LUCKY_VIBE', NULL, NULL, '시작은 쉬운데 멈춤이 어려울 수 있는 날라 지갑 닫기 알림을 걸어두면 안정적이에요.', 3, 0),
  (72, 'INSIGHT', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘은 가벼운 즐김이 적당해요. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 3, 2),
  (73, 'INSIGHT', 'FUNNY', 0, 100, NULL, NULL, NULL, '머리가 맑은 편라서 오늘은 1장 룰가 특히 중요해요.', 3, 1),
  (74, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '조금 예민한 편라서 오늘은 ‘더 사기’ 금지가 특히 중요해요.', 1, 0),
  (75, 'INSIGHT', 'WARM', 0, 100, NULL, NULL, NULL, '조금 예민한 편라서 오늘은 1장 룰가 특히 중요해요.', 3, 2),
  (76, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '계획대로 가면 편한 날라 ‘1번만’ 규칙을 걸어두면 안정적이에요.', 3, 1),
  (77, 'INSIGHT', 'WARM', 0, 100, NULL, NULL, NULL, '오늘은 소액이 더 어울려요. 재미는 좋지만, ‘한도’는 꼭 지켜요.', 1, 3),
  (78, 'INSIGHT', 'ANY', 0, 60, 'MONEY_TIGHT', NULL, NULL, '기분이 좋을수록 규칙이 필요해요.', 2, 3),
  (79, 'INSIGHT', 'FUNNY', 0, 100, NULL, NULL, NULL, '‘한도’가 당신의 행운템입니다.', 2, 1),
  (80, 'INSIGHT', 'DRY', 0, 100, NULL, NULL, NULL, '시작은 쉬운데 멈춤이 어려울 수 있는 날라 딱 1회 방문을 걸어두면 안정적이에요.', 3, 2),
  (81, 'WARNING', 'FUNNY', 0, 55, 'DONT_BUY_TODAY,MONEY_TIGHT', NULL, NULL, '오늘은 ‘한 번 더’가 위험한 날. 첫 장에서 멈추는 게 간지입니다. 😅', 3, 5),
  (82, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '스트레스 해소용 구매는 금물! 지금 필요한 건 휴식/정리/한숨 돌리기예요. 🙂', 3, 5),
  (83, 'WARNING', 'ANY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '지갑이 타이트한 날엔 재미도 부담이 될 수 있어요. 오늘은 대체 미션 추천 🎯 😅', 2, 3),
  (84, 'WARNING', 'FUNNY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑', 3, 6),
  (85, 'WARNING', 'FUNNY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '스트레스 해소용 구매는 금물! 지금 필요한 건 휴식/정리/한숨 돌리기예요. 📌', 4, 4),
  (86, 'WARNING', 'ANY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑ 😅', 2, 5),
  (87, 'WARNING', 'DRY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑', 3, 5),
  (88, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑ 😅', 3, 2),
  (89, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY,STRESS_HIGH', NULL, NULL, '스트레스 해소용 구매는 금물! 지금 필요한 건 휴식/정리/한숨 돌리기예요.', 3, 2),
  (90, 'WARNING', 'COOL', 0, 55, 'DONT_BUY_TODAY,MONEY_TIGHT', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑ 📌', 4, 2),
  (91, 'WARNING', 'ANY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '지갑이 타이트한 날엔 재미도 부담이 될 수 있어요. 오늘은 대체 미션 추천 🎯 😅', 2, 2),
  (92, 'WARNING', 'COOL', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '충동 신호가 올라왔어요. ‘한 장 룰’도 힘들면 그냥 쉬는 게 승리! 📌', 2, 2),
  (93, 'WARNING', 'DRY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '스트레스 해소용 구매는 금물! 지금 필요한 건 휴식/정리/한숨 돌리기예요. 📌', 3, 4),
  (94, 'WARNING', 'ANY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 ‘한 번 더’가 위험한 날. 첫 장에서 멈추는 게 간지입니다.', 4, 5),
  (95, 'WARNING', 'DRY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '스트레스 해소용 구매는 금물! 지금 필요한 건 휴식/정리/한숨 돌리기예요.', 3, 3),
  (96, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑ 📌', 3, 5),
  (97, 'WARNING', 'ANY', 0, 55, 'DONT_BUY_TODAY,STRESS_HIGH', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑ 😅', 3, 5),
  (98, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '지갑이 타이트한 날엔 재미도 부담이 될 수 있어요. 오늘은 대체 미션 추천 🎯 📌', 2, 6),
  (99, 'WARNING', 'DRY', 0, 55, 'DONT_BUY_TODAY,MONEY_TIGHT', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑ 😅', 2, 5),
  (100, 'WARNING', 'ANY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '지갑이 타이트한 날엔 재미도 부담이 될 수 있어요. 오늘은 대체 미션 추천 🎯 😅', 3, 6),
  (101, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '스트레스 해소용 구매는 금물! 지금 필요한 건 휴식/정리/한숨 돌리기예요. 🙂', 4, 4),
  (102, 'WARNING', 'COOL', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 ‘한 번 더’가 위험한 날. 첫 장에서 멈추는 게 간지입니다. 😅', 4, 4),
  (103, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑', 2, 5),
  (104, 'WARNING', 'DRY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '충동 신호가 올라왔어요. ‘한 장 룰’도 힘들면 그냥 쉬는 게 승리!', 4, 3),
  (105, 'WARNING', 'ANY', 0, 55, 'DONT_BUY_TODAY,STRESS_HIGH', NULL, NULL, '충동 신호가 올라왔어요. ‘한 장 룰’도 힘들면 그냥 쉬는 게 승리! 😅', 4, 3),
  (106, 'WARNING', 'ANY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 ‘한 번 더’가 위험한 날. 첫 장에서 멈추는 게 간지입니다. 😅', 2, 3),
  (107, 'WARNING', 'DRY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑ 🙂', 2, 2),
  (108, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY,MONEY_TIGHT', NULL, NULL, '오늘은 ‘한 번 더’가 위험한 날. 첫 장에서 멈추는 게 간지입니다. 🙂', 4, 5),
  (109, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑ 😅', 2, 5),
  (110, 'WARNING', 'FUNNY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '지갑이 타이트한 날엔 재미도 부담이 될 수 있어요. 오늘은 대체 미션 추천 🎯 🙂', 4, 5),
  (111, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '충동 신호가 올라왔어요. ‘한 장 룰’도 힘들면 그냥 쉬는 게 승리! 😅', 3, 4),
  (112, 'WARNING', 'FUNNY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑ 😅', 3, 2),
  (113, 'WARNING', 'ANY', 0, 55, 'DONT_BUY_TODAY,STRESS_HIGH', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑', 2, 3),
  (114, 'WARNING', 'DRY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '충동 신호가 올라왔어요. ‘한 장 룰’도 힘들면 그냥 쉬는 게 승리!', 3, 4),
  (115, 'WARNING', 'COOL', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑ 📌', 2, 3),
  (116, 'WARNING', 'ANY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 ‘한 번 더’가 위험한 날. 첫 장에서 멈추는 게 간지입니다. 😅', 4, 2),
  (117, 'WARNING', 'ANY', 0, 55, 'DONT_BUY_TODAY,MONEY_TIGHT', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑', 4, 6),
  (118, 'WARNING', 'ANY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑', 2, 4),
  (119, 'WARNING', 'FUNNY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '지갑이 타이트한 날엔 재미도 부담이 될 수 있어요. 오늘은 대체 미션 추천 🎯', 2, 2),
  (120, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 ‘한 번 더’가 위험한 날. 첫 장에서 멈추는 게 간지입니다.', 3, 6),
  (121, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY,STRESS_HIGH', NULL, NULL, '오늘은 ‘한 번 더’가 위험한 날. 첫 장에서 멈추는 게 간지입니다. 😅', 4, 6),
  (122, 'WARNING', 'FUNNY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '충동 신호가 올라왔어요. ‘한 장 룰’도 힘들면 그냥 쉬는 게 승리!', 2, 3),
  (123, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '스트레스 해소용 구매는 금물! 지금 필요한 건 휴식/정리/한숨 돌리기예요.', 4, 2),
  (124, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 ‘한 번 더’가 위험한 날. 첫 장에서 멈추는 게 간지입니다. 📌', 3, 5),
  (125, 'WARNING', 'FUNNY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑ 😅', 2, 2),
  (126, 'WARNING', 'FUNNY', 0, 55, 'DONT_BUY_TODAY,MONEY_TIGHT', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑ 😅', 3, 6),
  (127, 'WARNING', 'COOL', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '충동 신호가 올라왔어요. ‘한 장 룰’도 힘들면 그냥 쉬는 게 승리! 📌', 4, 2),
  (128, 'WARNING', 'FUNNY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 ‘한 번 더’가 위험한 날. 첫 장에서 멈추는 게 간지입니다.', 3, 3),
  (129, 'WARNING', 'FUNNY', 0, 55, 'DONT_BUY_TODAY,STRESS_HIGH', NULL, NULL, '오늘은 로또보다 PASS가 더 이득일 수 있어요. 한도/장수 규칙 없이 들어가면 후회 확률↑ 🙂', 2, 3),
  (130, 'WARNING', 'ANY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '충동 신호가 올라왔어요. ‘한 장 룰’도 힘들면 그냥 쉬는 게 승리!', 3, 2),
  (131, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '스트레스 해소용 구매는 금물! 지금 필요한 건 휴식/정리/한숨 돌리기예요.', 2, 6),
  (132, 'WARNING', 'DRY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '지갑이 타이트한 날엔 재미도 부담이 될 수 있어요. 오늘은 대체 미션 추천 🎯 😅', 4, 5),
  (133, 'WARNING', 'COOL', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '지갑이 타이트한 날엔 재미도 부담이 될 수 있어요. 오늘은 대체 미션 추천 🎯', 3, 2),
  (134, 'WARNING', 'DRY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '지갑이 타이트한 날엔 재미도 부담이 될 수 있어요. 오늘은 대체 미션 추천 🎯 🙂', 3, 6),
  (135, 'WARNING', 'WARM', 0, 55, 'DONT_BUY_TODAY,MONEY_TIGHT', NULL, NULL, '스트레스 해소용 구매는 금물! 지금 필요한 건 휴식/정리/한숨 돌리기예요. 🙂', 3, 5),
  (136, 'WARNING', 'ANY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '지갑이 타이트한 날엔 재미도 부담이 될 수 있어요. 오늘은 대체 미션 추천 🎯 🙂', 2, 2),
  (137, 'WARNING', 'DRY', 0, 55, 'DONT_BUY_TODAY,STRESS_HIGH', NULL, NULL, '스트레스 해소용 구매는 금물! 지금 필요한 건 휴식/정리/한숨 돌리기예요.', 2, 6),
  (138, 'WARNING', 'FUNNY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '스트레스 해소용 구매는 금물! 지금 필요한 건 휴식/정리/한숨 돌리기예요.', 3, 2),
  (139, 'WARNING', 'ANY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '충동 신호가 올라왔어요. ‘한 장 룰’도 힘들면 그냥 쉬는 게 승리! 🙂', 4, 2),
  (140, 'WARNING', 'FUNNY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '충동 신호가 올라왔어요. ‘한 장 룰’도 힘들면 그냥 쉬는 게 승리! 📌', 3, 2),
  (141, 'ALTERNATIVE', 'FUNNY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 친구에게 ‘오늘 PASS 선언’ 보내기. ☕', 2, 2),
  (142, 'ALTERNATIVE', 'FUNNY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 5분 산책 + 편의점에서 작은 간식 하나(로또 대신 소확행).', 2, 4),
  (143, 'ALTERNATIVE', 'COOL', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 친구에게 ‘오늘 PASS 선언’ 보내기. ☕', 3, 4),
  (144, 'ALTERNATIVE', 'ANY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 따뜻한 물/차 한 잔 마시고 숨 고르기. ☕', 3, 2),
  (145, 'ALTERNATIVE', 'ANY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 스트레칭 2분 + 눈 감고 10번 호흡. ✅', 1, 2),
  (146, 'ALTERNATIVE', 'ANY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 스트레칭 2분 + 눈 감고 10번 호흡.', 1, 2),
  (147, 'ALTERNATIVE', 'WARM', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 5분 산책 + 편의점에서 작은 간식 하나(로또 대신 소확행). ✅', 1, 2),
  (148, 'ALTERNATIVE', 'WARM', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 따뜻한 물/차 한 잔 마시고 숨 고르기.', 3, 4),
  (149, 'ALTERNATIVE', 'WARM', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 지출 메모 3줄 쓰고 오늘은 PASS. ✅', 1, 4),
  (150, 'ALTERNATIVE', 'ANY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 친구에게 ‘오늘 PASS 선언’ 보내기. 🌿', 3, 1),
  (151, 'ALTERNATIVE', 'FUNNY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 친구에게 ‘오늘 PASS 선언’ 보내기.', 1, 3),
  (152, 'ALTERNATIVE', 'ANY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 스트레칭 2분 + 눈 감고 10번 호흡.', 1, 2),
  (153, 'ALTERNATIVE', 'WARM', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 친구에게 ‘오늘 PASS 선언’ 보내기.', 2, 1),
  (154, 'ALTERNATIVE', 'COOL', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 따뜻한 물/차 한 잔 마시고 숨 고르기.', 3, 1),
  (155, 'ALTERNATIVE', 'DRY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 5분 산책 + 편의점에서 작은 간식 하나(로또 대신 소확행). ✅', 1, 2),
  (156, 'ALTERNATIVE', 'COOL', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 지출 메모 3줄 쓰고 오늘은 PASS. ☕', 3, 1),
  (157, 'ALTERNATIVE', 'COOL', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 스트레칭 2분 + 눈 감고 10번 호흡. ☕', 2, 3),
  (158, 'ALTERNATIVE', 'ANY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 친구에게 ‘오늘 PASS 선언’ 보내기. ☕', 3, 4),
  (159, 'ALTERNATIVE', 'ANY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 친구에게 ‘오늘 PASS 선언’ 보내기. 🌿', 3, 3),
  (160, 'ALTERNATIVE', 'DRY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '대체 행동: 지출 메모 3줄 쓰고 오늘은 PASS. ✅', 3, 2);
