-- V6__seed_longform_blocks.sql
INSERT INTO longform_block (id, section, tone, min_score, max_score, required_tags, blocked_tags, conditions_json, text_template, weight, priority) VALUES
  (1, 'OPENING', 'DRY', 0, 100, NULL, NULL, NULL, '오늘 리포트는 {MOOD_PHRASE}. 로또는 예측이 아니라 ‘연출’로만 즐겨요.', 1, 2),
  (2, 'OPENING', 'DRY', 0, 100, NULL, NULL, NULL, '한 줄로 말하면 {ONE_LINER}. 오늘은 {SOFTEN} 시작해봅시다.', 3, 3),
  (3, 'OPENING', 'WARM', 0, 100, NULL, NULL, NULL, '오늘 리포트는 {MOOD_PHRASE}. 로또는 예측이 아니라 ‘연출’로만 즐겨요.', 3, 4),
  (4, 'OPENING', 'DRY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "STABILITY", "op": "<=", "value": 40}]}', '오늘의 분위기: {MOOD_PHRASE}. {EMPHASIS} 책임 소비가 기본이에요.', 2, 0),
  (5, 'OPENING', 'DRY', 0, 100, NULL, NULL, NULL, '오늘의 분위기: {MOOD_PHRASE}. {EMPHASIS} 책임 소비가 기본이에요.', 1, 0),
  (6, 'OPENING', 'ANY', 0, 100, NULL, NULL, NULL, '오늘 리포트는 {MOOD_PHRASE}. 로또는 예측이 아니라 ‘연출’로만 즐겨요.', 1, 3),
  (7, 'OPENING', 'FUNNY', 0, 100, NULL, NULL, NULL, '생각보다 {MOOD_PHRASE}인 날이에요. 그래서 {RULE_HINT}를 먼저 잡는 게 좋아요.', 3, 1),
  (8, 'OPENING', 'ANY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": ">=", "value": 65}]}', '오늘 리포트는 {MOOD_PHRASE}. 로또는 예측이 아니라 ‘연출’로만 즐겨요.', 1, 4),
  (9, 'OPENING', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘 리포트는 {MOOD_PHRASE}. 로또는 예측이 아니라 ‘연출’로만 즐겨요.', 2, 4),
  (10, 'OPENING', 'DRY', 0, 100, NULL, NULL, NULL, '오늘 리포트는 {MOOD_PHRASE}. 로또는 예측이 아니라 ‘연출’로만 즐겨요.', 3, 3),
  (11, 'OPENING', 'DRY', 0, 100, NULL, NULL, NULL, '생각보다 {MOOD_PHRASE}인 날이에요. 그래서 {RULE_HINT}를 먼저 잡는 게 좋아요.', 1, 4),
  (12, 'OPENING', 'ANY', 0, 100, NULL, NULL, NULL, '생각보다 {MOOD_PHRASE}인 날이에요. 그래서 {RULE_HINT}를 먼저 잡는 게 좋아요.', 3, 4),
  (13, 'OPENING', 'COOL', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": ">=", "value": 70}]}', '오늘 리포트는 {MOOD_PHRASE}. 로또는 예측이 아니라 ‘연출’로만 즐겨요.', 2, 1),
  (14, 'OPENING', 'DRY', 0, 100, NULL, NULL, NULL, '생각보다 {MOOD_PHRASE}인 날이에요. 그래서 {RULE_HINT}를 먼저 잡는 게 좋아요.', 1, 3),
  (15, 'OPENING', 'FUNNY', 0, 100, NULL, NULL, NULL, '한 줄로 말하면 {ONE_LINER}. 오늘은 {SOFTEN} 시작해봅시다.', 3, 3),
  (16, 'OPENING', 'DRY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "RISK", "op": "<=", "value": 70}]}', '오늘 리포트는 {MOOD_PHRASE}. 로또는 예측이 아니라 ‘연출’로만 즐겨요.', 1, 4),
  (17, 'OPENING', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘 리포트는 {MOOD_PHRASE}. 로또는 예측이 아니라 ‘연출’로만 즐겨요.', 1, 3),
  (18, 'OPENING', 'FUNNY', 0, 100, NULL, NULL, NULL, '생각보다 {MOOD_PHRASE}인 날이에요. 그래서 {RULE_HINT}를 먼저 잡는 게 좋아요.', 1, 1),
  (19, 'OPENING', 'FUNNY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "STABILITY", "op": ">=", "value": 65}]}', '한 줄로 말하면 {ONE_LINER}. 오늘은 {SOFTEN} 시작해봅시다.', 2, 3),
  (20, 'OPENING', 'FUNNY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": ">=", "value": 75}]}', '생각보다 {MOOD_PHRASE}인 날이에요. 그래서 {RULE_HINT}를 먼저 잡는 게 좋아요.', 1, 1),
  (21, 'OPENING', 'ANY', 0, 100, NULL, NULL, NULL, '오늘의 분위기: {MOOD_PHRASE}. {EMPHASIS} 책임 소비가 기본이에요.', 2, 4),
  (22, 'OPENING', 'ANY', 0, 100, NULL, NULL, NULL, '오늘의 분위기: {MOOD_PHRASE}. {EMPHASIS} 책임 소비가 기본이에요.', 2, 0),
  (23, 'OPENING', 'ANY', 0, 100, NULL, NULL, NULL, '한 줄로 말하면 {ONE_LINER}. 오늘은 {SOFTEN} 시작해봅시다.', 2, 2),
  (24, 'OPENING', 'FUNNY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": ">=", "value": 35}]}', '오늘 리포트는 {MOOD_PHRASE}. 로또는 예측이 아니라 ‘연출’로만 즐겨요.', 2, 4),
  (25, 'OPENING', 'FUNNY', 0, 100, NULL, NULL, NULL, '생각보다 {MOOD_PHRASE}인 날이에요. 그래서 {RULE_HINT}를 먼저 잡는 게 좋아요.', 1, 4),
  (26, 'OPENING', 'WARM', 0, 100, NULL, NULL, NULL, '생각보다 {MOOD_PHRASE}인 날이에요. 그래서 {RULE_HINT}를 먼저 잡는 게 좋아요.', 3, 0),
  (27, 'OPENING', 'COOL', 0, 100, NULL, NULL, NULL, '생각보다 {MOOD_PHRASE}인 날이에요. 그래서 {RULE_HINT}를 먼저 잡는 게 좋아요.', 3, 4),
  (28, 'OPENING', 'WARM', 0, 100, NULL, NULL, NULL, '오늘 리포트는 {MOOD_PHRASE}. 로또는 예측이 아니라 ‘연출’로만 즐겨요.', 2, 3),
  (29, 'OPENING', 'ANY', 0, 100, NULL, NULL, NULL, '오늘의 분위기: {MOOD_PHRASE}. {EMPHASIS} 책임 소비가 기본이에요.', 2, 2),
  (30, 'OPENING', 'DRY', 0, 100, NULL, NULL, NULL, '생각보다 {MOOD_PHRASE}인 날이에요. 그래서 {RULE_HINT}를 먼저 잡는 게 좋아요.', 3, 3),
  (31, 'OPENING', 'ANY', 0, 100, NULL, NULL, NULL, '오늘의 분위기: {MOOD_PHRASE}. {EMPHASIS} 책임 소비가 기본이에요.', 2, 4),
  (32, 'OPENING', 'COOL', 0, 100, NULL, NULL, NULL, '오늘 리포트는 {MOOD_PHRASE}. 로또는 예측이 아니라 ‘연출’로만 즐겨요.', 3, 4),
  (33, 'OPENING', 'DRY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": ">=", "value": 40}]}', '오늘 리포트는 {MOOD_PHRASE}. 로또는 예측이 아니라 ‘연출’로만 즐겨요.', 1, 0),
  (34, 'OPENING', 'ANY', 0, 100, NULL, NULL, NULL, '오늘 리포트는 {MOOD_PHRASE}. 로또는 예측이 아니라 ‘연출’로만 즐겨요.', 3, 0),
  (35, 'OPENING', 'WARM', 0, 100, NULL, NULL, NULL, '오늘의 분위기: {MOOD_PHRASE}. {EMPHASIS} 책임 소비가 기본이에요.', 1, 2),
  (36, 'ANALYSIS', 'FUNNY', 0, 100, NULL, NULL, NULL, '응답 패턴을 보면 {SIGNAL_POS}가 보이지만, 동시에 {SIGNAL_NEG}도 있어요. 균형이 포인트입니다.', 3, 4),
  (37, 'ANALYSIS', 'DRY', 0, 100, NULL, NULL, NULL, '응답 패턴을 보면 {SIGNAL_POS}가 보이지만, 동시에 {SIGNAL_NEG}도 있어요. 균형이 포인트입니다.', 2, 0),
  (38, 'ANALYSIS', 'FUNNY', 0, 100, NULL, NULL, NULL, '응답 패턴을 보면 {SIGNAL_POS}가 보이지만, 동시에 {SIGNAL_NEG}도 있어요. 균형이 포인트입니다.', 3, 3),
  (39, 'ANALYSIS', 'COOL', 0, 100, 'IMPULSIVITY_HIGH', NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": "<=", "value": 75}]}', '오늘은 {SIGNAL_NEG} 쪽이 살짝 강할 수 있어요. 그래서 {STOP_RULE}이 중요합니다.', 1, 2),
  (40, 'ANALYSIS', 'WARM', 0, 100, 'MONEY_TIGHT', NULL, NULL, '전반적으로 {SIGNAL_POS} 기운이 있지만, {SIGNAL_NEG}가 끼어들면 만족도가 떨어질 수 있어요.', 3, 6),
  (41, 'ANALYSIS', 'ANY', 0, 100, NULL, NULL, NULL, '오늘은 {SIGNAL_NEG} 쪽이 살짝 강할 수 있어요. 그래서 {STOP_RULE}이 중요합니다.', 1, 0),
  (42, 'ANALYSIS', 'DRY', 0, 100, NULL, NULL, NULL, '전반적으로 {SIGNAL_POS} 기운이 있지만, {SIGNAL_NEG}가 끼어들면 만족도가 떨어질 수 있어요.', 1, 3),
  (43, 'ANALYSIS', 'ANY', 0, 100, NULL, NULL, NULL, '오늘은 {SIGNAL_NEG} 쪽이 살짝 강할 수 있어요. 그래서 {STOP_RULE}이 중요합니다.', 2, 1),
  (44, 'ANALYSIS', 'DRY', 0, 100, NULL, NULL, NULL, '오늘은 {SIGNAL_NEG} 쪽이 살짝 강할 수 있어요. 그래서 {STOP_RULE}이 중요합니다.', 3, 2),
  (45, 'ANALYSIS', 'WARM', 0, 100, NULL, NULL, NULL, '오늘은 {SIGNAL_NEG} 쪽이 살짝 강할 수 있어요. 그래서 {STOP_RULE}이 중요합니다.', 2, 2),
  (46, 'ANALYSIS', 'WARM', 0, 100, NULL, NULL, NULL, '전반적으로 {SIGNAL_POS} 기운이 있지만, {SIGNAL_NEG}가 끼어들면 만족도가 떨어질 수 있어요.', 3, 2),
  (47, 'ANALYSIS', 'WARM', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "IMPULSIVITY", "op": ">=", "value": 35}]}', '오늘은 {SIGNAL_NEG} 쪽이 살짝 강할 수 있어요. 그래서 {STOP_RULE}이 중요합니다.', 2, 0),
  (48, 'ANALYSIS', 'ANY', 0, 100, NULL, NULL, NULL, '전반적으로 {SIGNAL_POS} 기운이 있지만, {SIGNAL_NEG}가 끼어들면 만족도가 떨어질 수 있어요.', 2, 3),
  (49, 'ANALYSIS', 'FUNNY', 0, 100, NULL, NULL, NULL, '전반적으로 {SIGNAL_POS} 기운이 있지만, {SIGNAL_NEG}가 끼어들면 만족도가 떨어질 수 있어요.', 3, 3),
  (50, 'ANALYSIS', 'WARM', 0, 100, NULL, NULL, NULL, '오늘은 {SIGNAL_NEG} 쪽이 살짝 강할 수 있어요. 그래서 {STOP_RULE}이 중요합니다.', 2, 3),
  (51, 'ANALYSIS', 'FUNNY', 0, 100, NULL, NULL, NULL, '전반적으로 {SIGNAL_POS} 기운이 있지만, {SIGNAL_NEG}가 끼어들면 만족도가 떨어질 수 있어요.', 2, 4),
  (52, 'ANALYSIS', 'ANY', 0, 100, 'STABILITY_LOW', NULL, NULL, '오늘은 {SIGNAL_NEG} 쪽이 살짝 강할 수 있어요. 그래서 {STOP_RULE}이 중요합니다.', 3, 2),
  (53, 'ANALYSIS', 'DRY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "RISK", "op": ">=", "value": 40}]}', '응답 패턴을 보면 {SIGNAL_POS}가 보이지만, 동시에 {SIGNAL_NEG}도 있어요. 균형이 포인트입니다.', 1, 4),
  (54, 'ANALYSIS', 'COOL', 0, 100, NULL, NULL, NULL, '오늘은 {SIGNAL_NEG} 쪽이 살짝 강할 수 있어요. 그래서 {STOP_RULE}이 중요합니다.', 2, 4),
  (55, 'ANALYSIS', 'WARM', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "FIN_EASE", "op": ">=", "value": 75}]}', '전반적으로 {SIGNAL_POS} 기운이 있지만, {SIGNAL_NEG}가 끼어들면 만족도가 떨어질 수 있어요.', 2, 1),
  (56, 'ANALYSIS', 'WARM', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "RISK", "op": ">=", "value": 75}]}', '전반적으로 {SIGNAL_POS} 기운이 있지만, {SIGNAL_NEG}가 끼어들면 만족도가 떨어질 수 있어요.', 3, 1),
  (57, 'ANALYSIS', 'FUNNY', 0, 100, 'STABILITY_LOW', NULL, NULL, '오늘은 {SIGNAL_NEG} 쪽이 살짝 강할 수 있어요. 그래서 {STOP_RULE}이 중요합니다.', 1, 2),
  (58, 'ANALYSIS', 'COOL', 0, 100, NULL, NULL, NULL, '지표는 한 방향으로만 움직이지 않아요. {SIGNAL_POS} ↔ {SIGNAL_NEG}가 섞인 날로 읽혀요.', 1, 4),
  (59, 'ANALYSIS', 'ANY', 0, 100, NULL, NULL, NULL, '지표는 한 방향으로만 움직이지 않아요. {SIGNAL_POS} ↔ {SIGNAL_NEG}가 섞인 날로 읽혀요.', 3, 0),
  (60, 'ANALYSIS', 'WARM', 0, 100, NULL, NULL, NULL, '응답 패턴을 보면 {SIGNAL_POS}가 보이지만, 동시에 {SIGNAL_NEG}도 있어요. 균형이 포인트입니다.', 1, 4),
  (61, 'ANALYSIS', 'ANY', 0, 100, NULL, NULL, NULL, '전반적으로 {SIGNAL_POS} 기운이 있지만, {SIGNAL_NEG}가 끼어들면 만족도가 떨어질 수 있어요.', 1, 4),
  (62, 'ANALYSIS', 'COOL', 0, 100, NULL, NULL, NULL, '전반적으로 {SIGNAL_POS} 기운이 있지만, {SIGNAL_NEG}가 끼어들면 만족도가 떨어질 수 있어요.', 1, 1),
  (63, 'ANALYSIS', 'COOL', 0, 100, 'IMPULSIVITY_HIGH', NULL, '{"all": [{"type": "axis", "axis": "RISK", "op": ">=", "value": 65}]}', '오늘은 {SIGNAL_NEG} 쪽이 살짝 강할 수 있어요. 그래서 {STOP_RULE}이 중요합니다.', 2, 6),
  (64, 'ANALYSIS', 'DRY', 0, 100, NULL, NULL, NULL, '응답 패턴을 보면 {SIGNAL_POS}가 보이지만, 동시에 {SIGNAL_NEG}도 있어요. 균형이 포인트입니다.', 2, 2),
  (65, 'ANALYSIS', 'FUNNY', 0, 100, NULL, NULL, NULL, '응답 패턴을 보면 {SIGNAL_POS}가 보이지만, 동시에 {SIGNAL_NEG}도 있어요. 균형이 포인트입니다.', 3, 0),
  (66, 'ANALYSIS', 'COOL', 0, 100, NULL, NULL, NULL, '전반적으로 {SIGNAL_POS} 기운이 있지만, {SIGNAL_NEG}가 끼어들면 만족도가 떨어질 수 있어요.', 1, 0),
  (67, 'ANALYSIS', 'WARM', 0, 100, NULL, NULL, NULL, '오늘은 {SIGNAL_NEG} 쪽이 살짝 강할 수 있어요. 그래서 {STOP_RULE}이 중요합니다.', 2, 4),
  (68, 'ANALYSIS', 'WARM', 0, 100, NULL, NULL, NULL, '전반적으로 {SIGNAL_POS} 기운이 있지만, {SIGNAL_NEG}가 끼어들면 만족도가 떨어질 수 있어요.', 3, 0),
  (69, 'ANALYSIS', 'WARM', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": ">=", "value": 35}]}', '지표는 한 방향으로만 움직이지 않아요. {SIGNAL_POS} ↔ {SIGNAL_NEG}가 섞인 날로 읽혀요.', 2, 3),
  (70, 'ANALYSIS', 'FUNNY', 0, 100, NULL, NULL, NULL, '응답 패턴을 보면 {SIGNAL_POS}가 보이지만, 동시에 {SIGNAL_NEG}도 있어요. 균형이 포인트입니다.', 2, 2),
  (71, 'ANALYSIS', 'DRY', 0, 100, 'LUCKY_VIBE', NULL, '{"all": [{"type": "axis", "axis": "IMPULSIVITY", "op": "<=", "value": 40}]}', '응답 패턴을 보면 {SIGNAL_POS}가 보이지만, 동시에 {SIGNAL_NEG}도 있어요. 균형이 포인트입니다.', 3, 5),
  (72, 'ANALYSIS', 'WARM', 0, 100, NULL, NULL, NULL, '응답 패턴을 보면 {SIGNAL_POS}가 보이지만, 동시에 {SIGNAL_NEG}도 있어요. 균형이 포인트입니다.', 2, 4),
  (73, 'ANALYSIS', 'DRY', 0, 100, 'STABILITY_LOW', NULL, NULL, '지표는 한 방향으로만 움직이지 않아요. {SIGNAL_POS} ↔ {SIGNAL_NEG}가 섞인 날로 읽혀요.', 2, 6),
  (74, 'ANALYSIS', 'COOL', 0, 100, NULL, NULL, NULL, '전반적으로 {SIGNAL_POS} 기운이 있지만, {SIGNAL_NEG}가 끼어들면 만족도가 떨어질 수 있어요.', 3, 2),
  (75, 'ANALYSIS', 'WARM', 0, 100, 'LUCKY_VIBE', NULL, NULL, '지표는 한 방향으로만 움직이지 않아요. {SIGNAL_POS} ↔ {SIGNAL_NEG}가 섞인 날로 읽혀요.', 3, 2),
  (76, 'ANALYSIS', 'COOL', 0, 100, NULL, NULL, NULL, '오늘은 {SIGNAL_NEG} 쪽이 살짝 강할 수 있어요. 그래서 {STOP_RULE}이 중요합니다.', 1, 1),
  (77, 'ANALYSIS', 'DRY', 0, 100, NULL, NULL, NULL, '오늘은 {SIGNAL_NEG} 쪽이 살짝 강할 수 있어요. 그래서 {STOP_RULE}이 중요합니다.', 3, 1),
  (78, 'ANALYSIS', 'COOL', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "FIN_EASE", "op": ">=", "value": 40}]}', '오늘은 {SIGNAL_NEG} 쪽이 살짝 강할 수 있어요. 그래서 {STOP_RULE}이 중요합니다.', 1, 0),
  (79, 'ANALYSIS', 'COOL', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": ">=", "value": 70}]}', '응답 패턴을 보면 {SIGNAL_POS}가 보이지만, 동시에 {SIGNAL_NEG}도 있어요. 균형이 포인트입니다.', 2, 0),
  (80, 'ANALYSIS', 'DRY', 0, 100, NULL, NULL, NULL, '전반적으로 {SIGNAL_POS} 기운이 있지만, {SIGNAL_NEG}가 끼어들면 만족도가 떨어질 수 있어요.', 3, 4),
  (81, 'TIP', 'COOL', 0, 100, NULL, NULL, NULL, '팁 하나: {TIP_PHRASE}. 이 한 줄이 오늘 결과를 더 ‘좋은 기억’으로 만들어요.', 3, 3),
  (82, 'TIP', 'WARM', 0, 100, NULL, NULL, NULL, '{TIP_PHRASE}. 그리고 한 번 더: {STOP_RULE}을 미리 정해두면 흔들림이 줄어요.', 1, 1),
  (83, 'TIP', 'COOL', 0, 100, NULL, NULL, NULL, '오늘은 {TIP_PHRASE}가 정답에 가깝습니다. 작은 룰이 큰 후회를 막아요.', 1, 0),
  (84, 'TIP', 'ANY', 0, 100, NULL, NULL, NULL, '구매를 하든 말든, {TIP_PHRASE}만 지켜보세요. {CTA}', 3, 4),
  (85, 'TIP', 'WARM', 0, 100, NULL, NULL, NULL, '팁 하나: {TIP_PHRASE}. 이 한 줄이 오늘 결과를 더 ‘좋은 기억’으로 만들어요.', 2, 2),
  (86, 'TIP', 'ANY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "IMPULSIVITY", "op": "<=", "value": 65}]}', '구매를 하든 말든, {TIP_PHRASE}만 지켜보세요. {CTA}', 1, 0),
  (87, 'TIP', 'ANY', 0, 100, NULL, NULL, NULL, '팁 하나: {TIP_PHRASE}. 이 한 줄이 오늘 결과를 더 ‘좋은 기억’으로 만들어요.', 3, 1),
  (88, 'TIP', 'COOL', 0, 100, NULL, NULL, NULL, '오늘은 {TIP_PHRASE}가 정답에 가깝습니다. 작은 룰이 큰 후회를 막아요.', 2, 3),
  (89, 'TIP', 'FUNNY', 0, 100, NULL, NULL, NULL, '팁 하나: {TIP_PHRASE}. 이 한 줄이 오늘 결과를 더 ‘좋은 기억’으로 만들어요.', 1, 0),
  (90, 'TIP', 'DRY', 0, 100, NULL, NULL, NULL, '{TIP_PHRASE}. 그리고 한 번 더: {STOP_RULE}을 미리 정해두면 흔들림이 줄어요.', 1, 2),
  (91, 'TIP', 'WARM', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": "<=", "value": 70}]}', '오늘은 {TIP_PHRASE}가 정답에 가깝습니다. 작은 룰이 큰 후회를 막아요.', 2, 3),
  (92, 'TIP', 'DRY', 0, 100, NULL, NULL, NULL, '오늘은 {TIP_PHRASE}가 정답에 가깝습니다. 작은 룰이 큰 후회를 막아요.', 1, 2),
  (93, 'TIP', 'DRY', 0, 100, NULL, NULL, NULL, '팁 하나: {TIP_PHRASE}. 이 한 줄이 오늘 결과를 더 ‘좋은 기억’으로 만들어요.', 1, 0),
  (94, 'TIP', 'COOL', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "IMPULSIVITY", "op": "<=", "value": 35}]}', '{TIP_PHRASE}. 그리고 한 번 더: {STOP_RULE}을 미리 정해두면 흔들림이 줄어요.', 2, 4),
  (95, 'TIP', 'DRY', 0, 100, NULL, NULL, NULL, '구매를 하든 말든, {TIP_PHRASE}만 지켜보세요. {CTA}', 3, 1),
  (96, 'TIP', 'ANY', 0, 100, NULL, NULL, NULL, '{TIP_PHRASE}. 그리고 한 번 더: {STOP_RULE}을 미리 정해두면 흔들림이 줄어요.', 1, 1),
  (97, 'TIP', 'FUNNY', 0, 100, NULL, NULL, NULL, '{TIP_PHRASE}. 그리고 한 번 더: {STOP_RULE}을 미리 정해두면 흔들림이 줄어요.', 3, 3),
  (98, 'TIP', 'DRY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": ">=", "value": 70}]}', '오늘은 {TIP_PHRASE}가 정답에 가깝습니다. 작은 룰이 큰 후회를 막아요.', 2, 4),
  (99, 'TIP', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘은 {TIP_PHRASE}가 정답에 가깝습니다. 작은 룰이 큰 후회를 막아요.', 2, 1),
  (100, 'TIP', 'COOL', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": "<=", "value": 70}]}', '구매를 하든 말든, {TIP_PHRASE}만 지켜보세요. {CTA}', 3, 4),
  (101, 'TIP', 'FUNNY', 0, 100, NULL, NULL, NULL, '팁 하나: {TIP_PHRASE}. 이 한 줄이 오늘 결과를 더 ‘좋은 기억’으로 만들어요.', 1, 4),
  (102, 'TIP', 'COOL', 0, 100, NULL, NULL, NULL, '오늘은 {TIP_PHRASE}가 정답에 가깝습니다. 작은 룰이 큰 후회를 막아요.', 1, 2),
  (103, 'TIP', 'WARM', 0, 100, NULL, NULL, NULL, '오늘은 {TIP_PHRASE}가 정답에 가깝습니다. 작은 룰이 큰 후회를 막아요.', 3, 3),
  (104, 'TIP', 'WARM', 0, 100, NULL, NULL, NULL, '팁 하나: {TIP_PHRASE}. 이 한 줄이 오늘 결과를 더 ‘좋은 기억’으로 만들어요.', 2, 4),
  (105, 'TIP', 'WARM', 0, 100, NULL, NULL, NULL, '{TIP_PHRASE}. 그리고 한 번 더: {STOP_RULE}을 미리 정해두면 흔들림이 줄어요.', 1, 3),
  (106, 'TIP', 'WARM', 0, 100, NULL, NULL, NULL, '{TIP_PHRASE}. 그리고 한 번 더: {STOP_RULE}을 미리 정해두면 흔들림이 줄어요.', 3, 0),
  (107, 'TIP', 'WARM', 0, 100, NULL, NULL, NULL, '구매를 하든 말든, {TIP_PHRASE}만 지켜보세요. {CTA}', 3, 1),
  (108, 'TIP', 'WARM', 0, 100, NULL, NULL, NULL, '팁 하나: {TIP_PHRASE}. 이 한 줄이 오늘 결과를 더 ‘좋은 기억’으로 만들어요.', 1, 3),
  (109, 'TIP', 'DRY', 0, 100, NULL, NULL, NULL, '{TIP_PHRASE}. 그리고 한 번 더: {STOP_RULE}을 미리 정해두면 흔들림이 줄어요.', 3, 1),
  (110, 'TIP', 'FUNNY', 0, 100, NULL, NULL, NULL, '{TIP_PHRASE}. 그리고 한 번 더: {STOP_RULE}을 미리 정해두면 흔들림이 줄어요.', 3, 0),
  (111, 'TIP', 'COOL', 0, 100, NULL, NULL, NULL, '팁 하나: {TIP_PHRASE}. 이 한 줄이 오늘 결과를 더 ‘좋은 기억’으로 만들어요.', 2, 4),
  (112, 'TIP', 'ANY', 0, 100, NULL, NULL, NULL, '팁 하나: {TIP_PHRASE}. 이 한 줄이 오늘 결과를 더 ‘좋은 기억’으로 만들어요.', 1, 2),
  (113, 'TIP', 'FUNNY', 0, 100, NULL, NULL, NULL, '구매를 하든 말든, {TIP_PHRASE}만 지켜보세요. {CTA}', 3, 0),
  (114, 'TIP', 'COOL', 0, 100, NULL, NULL, NULL, '팁 하나: {TIP_PHRASE}. 이 한 줄이 오늘 결과를 더 ‘좋은 기억’으로 만들어요.', 2, 0),
  (115, 'TIP', 'COOL', 0, 100, NULL, NULL, NULL, '구매를 하든 말든, {TIP_PHRASE}만 지켜보세요. {CTA}', 3, 0),
  (116, 'CAUTION', 'FUNNY', 0, 40, NULL, NULL, NULL, '오늘은 쉬어가도 괜찮아요. {CAUTION_PHRASE}. 대신 {FUN_THING}로 기분 전환!', 2, 3),
  (117, 'CAUTION', 'COOL', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 쉬어가도 괜찮아요. {CAUTION_PHRASE}. 대신 {FUN_THING}로 기분 전환!', 3, 5),
  (118, 'CAUTION', 'COOL', 0, 40, 'DONT_BUY_TODAY', NULL, '{"all": [{"type": "axis", "axis": "IMPULSIVITY", "op": "<=", "value": 70}]}', '오늘은 {CAUTION_PHRASE}. PASS는 ‘포기’가 아니라 ‘선택’일 수 있어요.', 1, 4),
  (119, 'CAUTION', 'ANY', 0, 60, NULL, NULL, NULL, '오늘은 쉬어가도 괜찮아요. {CAUTION_PHRASE}. 대신 {FUN_THING}로 기분 전환!', 3, 1),
  (120, 'CAUTION', 'ANY', 0, 60, 'DONT_BUY_TODAY', NULL, '{"all": [{"type": "axis", "axis": "FIN_EASE", "op": ">=", "value": 40}]}', '과몰입 방지: {CAUTION_PHRASE}. {EMPHASIS} 지갑을 보호하는 날입니다.', 1, 5),
  (121, 'CAUTION', 'WARM', 0, 60, 'DONT_BUY_TODAY', NULL, '{"all": [{"type": "axis", "axis": "STABILITY", "op": "<=", "value": 40}]}', '과몰입 방지: {CAUTION_PHRASE}. {EMPHASIS} 지갑을 보호하는 날입니다.', 3, 7),
  (122, 'CAUTION', 'DRY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지: {CAUTION_PHRASE}. {EMPHASIS} 지갑을 보호하는 날입니다.', 2, 3),
  (123, 'CAUTION', 'FUNNY', 0, 45, 'DONT_BUY_TODAY', NULL, NULL, '경고 모드 발동! {CAUTION_PHRASE}. 오늘은 {BUDGET_SMALL} 선이 안전해요.', 3, 3),
  (124, 'CAUTION', 'FUNNY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 {CAUTION_PHRASE}. PASS는 ‘포기’가 아니라 ‘선택’일 수 있어요.', 3, 5),
  (125, 'CAUTION', 'FUNNY', 0, 45, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지: {CAUTION_PHRASE}. {EMPHASIS} 지갑을 보호하는 날입니다.', 2, 7),
  (126, 'CAUTION', 'COOL', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '경고 모드 발동! {CAUTION_PHRASE}. 오늘은 {BUDGET_SMALL} 선이 안전해요.', 1, 4),
  (127, 'CAUTION', 'COOL', 0, 45, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 {CAUTION_PHRASE}. PASS는 ‘포기’가 아니라 ‘선택’일 수 있어요.', 2, 3),
  (128, 'CAUTION', 'WARM', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '경고 모드 발동! {CAUTION_PHRASE}. 오늘은 {BUDGET_SMALL} 선이 안전해요.', 2, 3),
  (129, 'CAUTION', 'ANY', 0, 55, NULL, NULL, NULL, '오늘은 쉬어가도 괜찮아요. {CAUTION_PHRASE}. 대신 {FUN_THING}로 기분 전환!', 1, 2),
  (130, 'CAUTION', 'ANY', 0, 45, NULL, NULL, NULL, '과몰입 방지: {CAUTION_PHRASE}. {EMPHASIS} 지갑을 보호하는 날입니다.', 2, 3),
  (131, 'CAUTION', 'ANY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 쉬어가도 괜찮아요. {CAUTION_PHRASE}. 대신 {FUN_THING}로 기분 전환!', 1, 5),
  (132, 'CAUTION', 'ANY', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '경고 모드 발동! {CAUTION_PHRASE}. 오늘은 {BUDGET_SMALL} 선이 안전해요.', 3, 7),
  (133, 'CAUTION', 'ANY', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 {CAUTION_PHRASE}. PASS는 ‘포기’가 아니라 ‘선택’일 수 있어요.', 3, 4),
  (134, 'CAUTION', 'COOL', 0, 45, NULL, NULL, '{"all": [{"type": "axis", "axis": "IMPULSIVITY", "op": ">=", "value": 70}]}', '오늘은 쉬어가도 괜찮아요. {CAUTION_PHRASE}. 대신 {FUN_THING}로 기분 전환!', 1, 0),
  (135, 'CAUTION', 'COOL', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지: {CAUTION_PHRASE}. {EMPHASIS} 지갑을 보호하는 날입니다.', 3, 4),
  (136, 'CAUTION', 'COOL', 0, 60, NULL, NULL, NULL, '오늘은 {CAUTION_PHRASE}. PASS는 ‘포기’가 아니라 ‘선택’일 수 있어요.', 1, 3),
  (137, 'CAUTION', 'ANY', 0, 60, NULL, NULL, NULL, '경고 모드 발동! {CAUTION_PHRASE}. 오늘은 {BUDGET_SMALL} 선이 안전해요.', 3, 4),
  (138, 'CAUTION', 'ANY', 0, 55, NULL, NULL, NULL, '오늘은 {CAUTION_PHRASE}. PASS는 ‘포기’가 아니라 ‘선택’일 수 있어요.', 2, 1),
  (139, 'CAUTION', 'WARM', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 쉬어가도 괜찮아요. {CAUTION_PHRASE}. 대신 {FUN_THING}로 기분 전환!', 3, 4),
  (140, 'CAUTION', 'FUNNY', 0, 45, NULL, NULL, NULL, '오늘은 {CAUTION_PHRASE}. PASS는 ‘포기’가 아니라 ‘선택’일 수 있어요.', 1, 1),
  (141, 'CAUTION', 'COOL', 0, 40, 'DONT_BUY_TODAY', NULL, NULL, '경고 모드 발동! {CAUTION_PHRASE}. 오늘은 {BUDGET_SMALL} 선이 안전해요.', 1, 6),
  (142, 'CAUTION', 'DRY', 0, 40, NULL, NULL, NULL, '오늘은 쉬어가도 괜찮아요. {CAUTION_PHRASE}. 대신 {FUN_THING}로 기분 전환!', 2, 2),
  (143, 'CAUTION', 'ANY', 0, 45, NULL, NULL, NULL, '오늘은 {CAUTION_PHRASE}. PASS는 ‘포기’가 아니라 ‘선택’일 수 있어요.', 2, 4),
  (144, 'CAUTION', 'COOL', 0, 60, NULL, NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": "<=", "value": 75}]}', '경고 모드 발동! {CAUTION_PHRASE}. 오늘은 {BUDGET_SMALL} 선이 안전해요.', 2, 0),
  (145, 'CAUTION', 'ANY', 0, 40, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": ">=", "value": 35}]}', '오늘은 쉬어가도 괜찮아요. {CAUTION_PHRASE}. 대신 {FUN_THING}로 기분 전환!', 1, 2),
  (146, 'CAUTION', 'COOL', 0, 55, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 쉬어가도 괜찮아요. {CAUTION_PHRASE}. 대신 {FUN_THING}로 기분 전환!', 2, 6),
  (147, 'CAUTION', 'DRY', 0, 45, 'DONT_BUY_TODAY', NULL, NULL, '과몰입 방지: {CAUTION_PHRASE}. {EMPHASIS} 지갑을 보호하는 날입니다.', 1, 5),
  (148, 'CAUTION', 'WARM', 0, 60, 'DONT_BUY_TODAY', NULL, NULL, '오늘은 쉬어가도 괜찮아요. {CAUTION_PHRASE}. 대신 {FUN_THING}로 기분 전환!', 2, 3),
  (149, 'CAUTION', 'WARM', 0, 60, NULL, NULL, NULL, '경고 모드 발동! {CAUTION_PHRASE}. 오늘은 {BUDGET_SMALL} 선이 안전해요.', 3, 1),
  (150, 'CAUTION', 'FUNNY', 0, 55, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": ">=", "value": 75}]}', '오늘은 쉬어가도 괜찮아요. {CAUTION_PHRASE}. 대신 {FUN_THING}로 기분 전환!', 1, 4),
  (151, 'STRATEGY', 'WARM', 0, 100, 'MONEY_EASY', NULL, NULL, '오늘의 전략은 간단해요: {STRATEGY_PHRASE}. 복잡할수록 충동이 커져요.', 3, 1),
  (152, 'STRATEGY', 'DRY', 0, 100, NULL, NULL, NULL, '오늘의 전략은 간단해요: {STRATEGY_PHRASE}. 복잡할수록 충동이 커져요.', 2, 2),
  (153, 'STRATEGY', 'WARM', 0, 100, NULL, NULL, NULL, '전략 카드 요약: {STRATEGY_PHRASE}. {TIME_WINDOW} 안에 마무리하는 게 깔끔합니다.', 1, 1),
  (154, 'STRATEGY', 'WARM', 0, 100, 'MONEY_EASY', NULL, NULL, '{STRATEGY_PHRASE}. 그리고 ‘멈춤’은 {STOP_RULE}로 고정!', 3, 0),
  (155, 'STRATEGY', 'WARM', 0, 100, NULL, NULL, NULL, '전략 카드 요약: {STRATEGY_PHRASE}. {TIME_WINDOW} 안에 마무리하는 게 깔끔합니다.', 3, 3),
  (156, 'STRATEGY', 'ANY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": "<=", "value": 65}]}', '오늘의 전략은 간단해요: {STRATEGY_PHRASE}. 복잡할수록 충동이 커져요.', 2, 2),
  (157, 'STRATEGY', 'FUNNY', 0, 100, NULL, NULL, NULL, '{STRATEGY_PHRASE}. 그리고 ‘멈춤’은 {STOP_RULE}로 고정!', 2, 2),
  (158, 'STRATEGY', 'WARM', 0, 100, NULL, NULL, NULL, '핵심 룰: {BUDGET_SMALL} + {STOP_RULE}. 이 조합이 오늘의 승률(만족도)을 올려요.', 2, 2),
  (159, 'STRATEGY', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘의 전략은 간단해요: {STRATEGY_PHRASE}. 복잡할수록 충동이 커져요.', 1, 4),
  (160, 'STRATEGY', 'COOL', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": ">=", "value": 70}]}', '오늘의 전략은 간단해요: {STRATEGY_PHRASE}. 복잡할수록 충동이 커져요.', 2, 0),
  (161, 'STRATEGY', 'WARM', 0, 100, 'SELF_CONTROL', NULL, NULL, '{STRATEGY_PHRASE}. 그리고 ‘멈춤’은 {STOP_RULE}로 고정!', 2, 1),
  (162, 'STRATEGY', 'COOL', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": ">=", "value": 75}]}', '전략 카드 요약: {STRATEGY_PHRASE}. {TIME_WINDOW} 안에 마무리하는 게 깔끔합니다.', 2, 3),
  (163, 'STRATEGY', 'FUNNY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "FIN_EASE", "op": ">=", "value": 75}]}', '오늘의 전략은 간단해요: {STRATEGY_PHRASE}. 복잡할수록 충동이 커져요.', 3, 2),
  (164, 'STRATEGY', 'FUNNY', 0, 100, 'STRESS_HIGH', NULL, NULL, '{STRATEGY_PHRASE}. 그리고 ‘멈춤’은 {STOP_RULE}로 고정!', 3, 1),
  (165, 'STRATEGY', 'DRY', 0, 100, NULL, NULL, NULL, '오늘의 전략은 간단해요: {STRATEGY_PHRASE}. 복잡할수록 충동이 커져요.', 2, 3),
  (166, 'STRATEGY', 'FUNNY', 0, 100, 'MONEY_EASY', NULL, NULL, '{STRATEGY_PHRASE}. 그리고 ‘멈춤’은 {STOP_RULE}로 고정!', 1, 0),
  (167, 'STRATEGY', 'DRY', 0, 100, NULL, NULL, NULL, '핵심 룰: {BUDGET_SMALL} + {STOP_RULE}. 이 조합이 오늘의 승률(만족도)을 올려요.', 3, 2),
  (168, 'STRATEGY', 'FUNNY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "STABILITY", "op": "<=", "value": 65}]}', '{STRATEGY_PHRASE}. 그리고 ‘멈춤’은 {STOP_RULE}로 고정!', 2, 2),
  (169, 'STRATEGY', 'ANY', 0, 100, NULL, NULL, NULL, '{STRATEGY_PHRASE}. 그리고 ‘멈춤’은 {STOP_RULE}로 고정!', 1, 4),
  (170, 'STRATEGY', 'DRY', 0, 100, NULL, NULL, NULL, '{STRATEGY_PHRASE}. 그리고 ‘멈춤’은 {STOP_RULE}로 고정!', 1, 3),
  (171, 'STRATEGY', 'ANY', 0, 100, NULL, NULL, NULL, '오늘의 전략은 간단해요: {STRATEGY_PHRASE}. 복잡할수록 충동이 커져요.', 2, 1),
  (172, 'STRATEGY', 'COOL', 0, 100, 'STRESS_HIGH', NULL, NULL, '오늘의 전략은 간단해요: {STRATEGY_PHRASE}. 복잡할수록 충동이 커져요.', 2, 4),
  (173, 'STRATEGY', 'FUNNY', 0, 100, 'ENERGY_HIGH_TAG', NULL, NULL, '{STRATEGY_PHRASE}. 그리고 ‘멈춤’은 {STOP_RULE}로 고정!', 3, 2),
  (174, 'STRATEGY', 'DRY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "FIN_EASE", "op": ">=", "value": 35}]}', '{STRATEGY_PHRASE}. 그리고 ‘멈춤’은 {STOP_RULE}로 고정!', 1, 2),
  (175, 'STRATEGY', 'WARM', 0, 100, NULL, NULL, NULL, '전략 카드 요약: {STRATEGY_PHRASE}. {TIME_WINDOW} 안에 마무리하는 게 깔끔합니다.', 2, 0),
  (176, 'STRATEGY', 'COOL', 0, 100, 'ENERGY_HIGH_TAG', NULL, NULL, '{STRATEGY_PHRASE}. 그리고 ‘멈춤’은 {STOP_RULE}로 고정!', 1, 4),
  (177, 'STRATEGY', 'ANY', 0, 100, NULL, NULL, NULL, '오늘의 전략은 간단해요: {STRATEGY_PHRASE}. 복잡할수록 충동이 커져요.', 1, 3),
  (178, 'STRATEGY', 'ANY', 0, 100, NULL, NULL, NULL, '{STRATEGY_PHRASE}. 그리고 ‘멈춤’은 {STOP_RULE}로 고정!', 2, 2),
  (179, 'STRATEGY', 'FUNNY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "OPTIMISM", "op": "<=", "value": 40}]}', '핵심 룰: {BUDGET_SMALL} + {STOP_RULE}. 이 조합이 오늘의 승률(만족도)을 올려요.', 3, 3),
  (180, 'STRATEGY', 'COOL', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "STABILITY", "op": "<=", "value": 35}]}', '오늘의 전략은 간단해요: {STRATEGY_PHRASE}. 복잡할수록 충동이 커져요.', 3, 0),
  (181, 'STRATEGY', 'ANY', 0, 100, NULL, NULL, NULL, '핵심 룰: {BUDGET_SMALL} + {STOP_RULE}. 이 조합이 오늘의 승률(만족도)을 올려요.', 3, 2),
  (182, 'STRATEGY', 'FUNNY', 0, 100, NULL, NULL, NULL, '전략 카드 요약: {STRATEGY_PHRASE}. {TIME_WINDOW} 안에 마무리하는 게 깔끔합니다.', 3, 1),
  (183, 'STRATEGY', 'COOL', 0, 100, 'MONEY_EASY', NULL, NULL, '전략 카드 요약: {STRATEGY_PHRASE}. {TIME_WINDOW} 안에 마무리하는 게 깔끔합니다.', 3, 1),
  (184, 'STRATEGY', 'WARM', 0, 100, NULL, NULL, NULL, '{STRATEGY_PHRASE}. 그리고 ‘멈춤’은 {STOP_RULE}로 고정!', 1, 1),
  (185, 'STRATEGY', 'DRY', 0, 100, NULL, NULL, NULL, '핵심 룰: {BUDGET_SMALL} + {STOP_RULE}. 이 조합이 오늘의 승률(만족도)을 올려요.', 3, 4),
  (186, 'CONCLUSION', 'DRY', 0, 100, NULL, NULL, NULL, '오늘의 결론은 {CONCLUDE_PHRASE}. {CTA}', 2, 2),
  (187, 'CONCLUSION', 'ANY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '한 줄 결론: {CONCLUDE_PHRASE}. 재미는 OK, 무리는 NO.', 1, 7),
  (188, 'CONCLUSION', 'ANY', 0, 100, 'DONT_BUY_TODAY', NULL, '{"all": [{"type": "axis", "axis": "STABILITY", "op": "<=", "value": 70}]}', '한 줄 결론: {CONCLUDE_PHRASE}. 재미는 OK, 무리는 NO.', 1, 6),
  (189, 'CONCLUSION', 'WARM', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '{CONCLUDE_PHRASE}. 다음엔 더 가볍게 즐길 수 있도록 한도만 기억해요.', 1, 3),
  (190, 'CONCLUSION', 'ANY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '결론: {CONCLUDE_PHRASE}. 당첨 예측이 아니라, ‘오늘의 소비 리듬’ 리포트입니다.', 2, 6),
  (191, 'CONCLUSION', 'COOL', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "STABILITY", "op": "<=", "value": 65}]}', '결론: {CONCLUDE_PHRASE}. 당첨 예측이 아니라, ‘오늘의 소비 리듬’ 리포트입니다.', 3, 1),
  (192, 'CONCLUSION', 'ANY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '한 줄 결론: {CONCLUDE_PHRASE}. 재미는 OK, 무리는 NO.', 3, 5),
  (193, 'CONCLUSION', 'COOL', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '결론: {CONCLUDE_PHRASE}. 당첨 예측이 아니라, ‘오늘의 소비 리듬’ 리포트입니다.', 3, 6),
  (194, 'CONCLUSION', 'COOL', 0, 100, NULL, NULL, NULL, '한 줄 결론: {CONCLUDE_PHRASE}. 재미는 OK, 무리는 NO.', 2, 4),
  (195, 'CONCLUSION', 'FUNNY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '결론: {CONCLUDE_PHRASE}. 당첨 예측이 아니라, ‘오늘의 소비 리듬’ 리포트입니다.', 2, 5),
  (196, 'CONCLUSION', 'DRY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '오늘의 결론은 {CONCLUDE_PHRASE}. {CTA}', 3, 3),
  (197, 'CONCLUSION', 'COOL', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '결론: {CONCLUDE_PHRASE}. 당첨 예측이 아니라, ‘오늘의 소비 리듬’ 리포트입니다.', 2, 6),
  (198, 'CONCLUSION', 'FUNNY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '{CONCLUDE_PHRASE}. 다음엔 더 가볍게 즐길 수 있도록 한도만 기억해요.', 1, 3),
  (199, 'CONCLUSION', 'FUNNY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '{CONCLUDE_PHRASE}. 다음엔 더 가볍게 즐길 수 있도록 한도만 기억해요.', 3, 4),
  (200, 'CONCLUSION', 'WARM', 0, 100, 'DONT_BUY_TODAY', NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": "<=", "value": 40}]}', '한 줄 결론: {CONCLUDE_PHRASE}. 재미는 OK, 무리는 NO.', 2, 5);

INSERT INTO longform_block (id, section, tone, min_score, max_score, required_tags, blocked_tags, conditions_json, text_template, weight, priority) VALUES
  (201, 'CONCLUSION', 'FUNNY', 0, 100, NULL, NULL, NULL, '결론: {CONCLUDE_PHRASE}. 당첨 예측이 아니라, ‘오늘의 소비 리듬’ 리포트입니다.', 1, 3),
  (202, 'CONCLUSION', 'WARM', 0, 100, NULL, NULL, NULL, '{CONCLUDE_PHRASE}. 다음엔 더 가볍게 즐길 수 있도록 한도만 기억해요.', 1, 1),
  (203, 'CONCLUSION', 'DRY', 0, 100, NULL, NULL, NULL, '한 줄 결론: {CONCLUDE_PHRASE}. 재미는 OK, 무리는 NO.', 3, 2),
  (204, 'CONCLUSION', 'ANY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '{CONCLUDE_PHRASE}. 다음엔 더 가볍게 즐길 수 있도록 한도만 기억해요.', 2, 7),
  (205, 'CONCLUSION', 'FUNNY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '오늘의 결론은 {CONCLUDE_PHRASE}. {CTA}', 1, 5),
  (206, 'CONCLUSION', 'COOL', 0, 100, NULL, NULL, NULL, '{CONCLUDE_PHRASE}. 다음엔 더 가볍게 즐길 수 있도록 한도만 기억해요.', 2, 2),
  (207, 'CONCLUSION', 'ANY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "STABILITY", "op": "<=", "value": 65}]}', '한 줄 결론: {CONCLUDE_PHRASE}. 재미는 OK, 무리는 NO.', 3, 1),
  (208, 'CONCLUSION', 'DRY', 0, 100, NULL, NULL, NULL, '결론: {CONCLUDE_PHRASE}. 당첨 예측이 아니라, ‘오늘의 소비 리듬’ 리포트입니다.', 2, 4),
  (209, 'CONCLUSION', 'DRY', 0, 100, 'DONT_BUY_TODAY', NULL, NULL, '오늘의 결론은 {CONCLUDE_PHRASE}. {CTA}', 1, 5),
  (210, 'CONCLUSION', 'FUNNY', 0, 100, NULL, NULL, NULL, '결론: {CONCLUDE_PHRASE}. 당첨 예측이 아니라, ‘오늘의 소비 리듬’ 리포트입니다.', 1, 2),
  (211, 'FUN', 'DRY', 0, 100, NULL, NULL, NULL, '{FUN_THING}. 이 정도면 오늘의 운세 연출 완료!', 1, 0),
  (212, 'FUN', 'COOL', 0, 100, NULL, NULL, NULL, '재미 미션: {FUN_THING}. 성공하면 오늘 운세 +1(기분)입니다.', 2, 3),
  (213, 'FUN', 'COOL', 0, 100, NULL, NULL, NULL, '재미 미션: {FUN_THING}. 성공하면 오늘 운세 +1(기분)입니다.', 3, 0),
  (214, 'FUN', 'COOL', 0, 100, NULL, NULL, NULL, '미션 카드: {FUN_THING}. 결과는 ‘웃음’이면 합격!', 1, 0),
  (215, 'FUN', 'FUNNY', 0, 100, NULL, NULL, NULL, '오늘의 소소한 미션은 {FUN_THING}. 로또보다 이게 더 확실한 행복일지도요.', 1, 4),
  (216, 'FUN', 'WARM', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "RISK", "op": ">=", "value": 70}]}', '재미 미션: {FUN_THING}. 성공하면 오늘 운세 +1(기분)입니다.', 3, 0),
  (217, 'FUN', 'WARM', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": ">=", "value": 40}]}', '미션 카드: {FUN_THING}. 결과는 ‘웃음’이면 합격!', 2, 2),
  (218, 'FUN', 'FUNNY', 0, 100, NULL, NULL, '{"all": [{"type": "axis", "axis": "ENERGY", "op": "<=", "value": 65}]}', '오늘의 소소한 미션은 {FUN_THING}. 로또보다 이게 더 확실한 행복일지도요.', 2, 0),
  (219, 'FUN', 'COOL', 0, 100, NULL, NULL, NULL, '재미 미션: {FUN_THING}. 성공하면 오늘 운세 +1(기분)입니다.', 2, 2),
  (220, 'FUN', 'WARM', 0, 100, NULL, NULL, NULL, '오늘의 소소한 미션은 {FUN_THING}. 로또보다 이게 더 확실한 행복일지도요.', 3, 0);
