-- V7__seed_phrase_pool.sql
INSERT INTO phrase_pool (id, slot_key, tone, text, weight) VALUES
  (1, 'MOOD_PHRASE', 'ANY', '무드가 가볍게 떠오르는 느낌이에요', 3),
  (2, 'MOOD_PHRASE', 'DRY', '무리하면 피곤해지는 타입의 날이에요 (중요)', 1),
  (3, 'MOOD_PHRASE', 'ANY', '무드가 가볍게 떠오르는 느낌이에요', 2),
  (4, 'MOOD_PHRASE', 'WARM', '컨디션이 출렁일 수 있어요', 1),
  (5, 'MOOD_PHRASE', 'DRY', '무드가 가볍게 떠오르는 느낌이에요 (추천)', 3),
  (6, 'MOOD_PHRASE', 'DRY', '무드가 가볍게 떠오르는 느낌이에요', 2),
  (7, 'MOOD_PHRASE', 'WARM', '오늘은 ‘적당히’가 잘 맞는 날이에요', 1),
  (8, 'MOOD_PHRASE', 'COOL', '무리하면 피곤해지는 타입의 날이에요', 3),
  (9, 'MOOD_PHRASE', 'ANY', '컨디션이 출렁일 수 있어요', 2),
  (10, 'MOOD_PHRASE', 'COOL', '오늘은 ‘적당히’가 잘 맞는 날이에요', 2),
  (11, 'MOOD_PHRASE', 'COOL', '기분이 살짝 들뜬 상태예요', 1),
  (12, 'MOOD_PHRASE', 'ANY', '차분하게 정리되는 흐름이에요', 2),
  (13, 'MOOD_PHRASE', 'DRY', '기분이 살짝 들뜬 상태예요!', 1),
  (14, 'MOOD_PHRASE', 'COOL', '조금 예민해질 수 있는 날이에요!', 2),
  (15, 'MOOD_PHRASE', 'DRY', '여유를 챙기면 더 좋아져요', 2),
  (16, 'MOOD_PHRASE', 'ANY', '평소보다 생각이 선명한 편이에요', 1),
  (17, 'MOOD_PHRASE', 'ANY', '기분이 살짝 들뜬 상태예요', 1),
  (18, 'MOOD_PHRASE', 'FUNNY', '여유를 챙기면 더 좋아져요 (추천)', 1),
  (19, 'MOOD_PHRASE', 'ANY', '여유를 챙기면 더 좋아져요', 3),
  (20, 'MOOD_PHRASE', 'WARM', '조금 예민해질 수 있는 날이에요', 1),
  (21, 'ONE_LINER', 'ANY', '지갑을 지키면 마음도 편함', 1),
  (22, 'ONE_LINER', 'FUNNY', 'PASS도 전략', 2),
  (23, 'ONE_LINER', 'COOL', '룰이 있으면 더 행복 (중요)', 3),
  (24, 'ONE_LINER', 'DRY', '지갑을 지키면 마음도 편함 🙂', 3),
  (25, 'ONE_LINER', 'DRY', '룰이 있으면 더 행복!', 2),
  (26, 'ONE_LINER', 'COOL', '한도는 사랑', 3),
  (27, 'ONE_LINER', 'DRY', '한도는 사랑!', 1),
  (28, 'ONE_LINER', 'FUNNY', '멈출 줄 알면 이긴다', 2),
  (29, 'ONE_LINER', 'ANY', '재미는 OK, 무리는 NO', 1),
  (30, 'ONE_LINER', 'DRY', '지갑을 지키면 마음도 편함', 3),
  (31, 'ONE_LINER', 'ANY', '기분 좋을수록 규칙', 1),
  (32, 'ONE_LINER', 'DRY', '한 장이면 충분', 2),
  (33, 'ONE_LINER', 'COOL', '재미는 OK, 무리는 NO', 3),
  (34, 'ONE_LINER', 'FUNNY', '한도는 사랑', 1),
  (35, 'ONE_LINER', 'DRY', '룰이 있으면 더 행복', 2),
  (36, 'ONE_LINER', 'WARM', '한 장이면 충분', 3),
  (37, 'ONE_LINER', 'ANY', '한도는 사랑 (중요)', 3),
  (38, 'ONE_LINER', 'DRY', '운은 연출, 소비는 현실', 3),
  (39, 'ONE_LINER', 'DRY', '한도는 사랑', 1),
  (40, 'ONE_LINER', 'COOL', '운은 연출, 소비는 현실', 1),
  (41, 'SOFTEN', 'FUNNY', '짧게', 3),
  (42, 'SOFTEN', 'COOL', '담백하게', 2),
  (43, 'SOFTEN', 'ANY', '부담 없이', 2),
  (44, 'SOFTEN', 'ANY', '가볍게 (추천)', 3),
  (45, 'SOFTEN', 'DRY', '짧게', 2),
  (46, 'SOFTEN', 'FUNNY', '가볍게', 2),
  (47, 'SOFTEN', 'ANY', '가볍게', 3),
  (48, 'SOFTEN', 'COOL', '천천히', 1),
  (49, 'SOFTEN', 'WARM', '담백하게', 2),
  (50, 'SOFTEN', 'FUNNY', '천천히 🙂', 1),
  (51, 'SOFTEN', 'ANY', '가볍게', 3),
  (52, 'SOFTEN', 'WARM', '부담 없이 (중요)', 3),
  (53, 'SOFTEN', 'WARM', '담백하게!', 3),
  (54, 'SOFTEN', 'ANY', '부담 없이 (중요)', 1),
  (55, 'SOFTEN', 'DRY', '짧게', 3),
  (56, 'SOFTEN', 'COOL', '부담 없이', 2),
  (57, 'SOFTEN', 'ANY', '짧게', 3),
  (58, 'SOFTEN', 'ANY', '가볍게', 2),
  (59, 'SOFTEN', 'WARM', '가볍게 (중요)', 1),
  (60, 'SOFTEN', 'FUNNY', '천천히!', 3),
  (61, 'EMPHASIS', 'COOL', '항상', 3),
  (62, 'EMPHASIS', 'DRY', '무조건 (추천)', 1),
  (63, 'EMPHASIS', 'COOL', '특히!', 3),
  (64, 'EMPHASIS', 'WARM', '가장 먼저', 1),
  (65, 'EMPHASIS', 'DRY', '무조건', 1),
  (66, 'EMPHASIS', 'DRY', '무조건 (중요)', 2),
  (67, 'EMPHASIS', 'FUNNY', '가장 먼저 (중요)', 3),
  (68, 'EMPHASIS', 'ANY', '무엇보다', 2),
  (69, 'EMPHASIS', 'ANY', '무엇보다', 1),
  (70, 'EMPHASIS', 'COOL', '무엇보다', 2),
  (71, 'EMPHASIS', 'COOL', '무조건', 2),
  (72, 'EMPHASIS', 'FUNNY', '무엇보다', 2),
  (73, 'EMPHASIS', 'WARM', '가장 먼저', 1),
  (74, 'EMPHASIS', 'WARM', '가장 먼저', 3),
  (75, 'EMPHASIS', 'COOL', '무엇보다', 3),
  (76, 'EMPHASIS', 'WARM', '항상 (추천)', 1),
  (77, 'EMPHASIS', 'WARM', '항상', 2),
  (78, 'EMPHASIS', 'WARM', '가장 먼저', 3),
  (79, 'EMPHASIS', 'FUNNY', '무조건', 3),
  (80, 'EMPHASIS', 'FUNNY', '가장 먼저 🙂', 3),
  (81, 'RULE_HINT', 'DRY', '한도 고정', 2),
  (82, 'RULE_HINT', 'WARM', '한도 고정', 3),
  (83, 'RULE_HINT', 'FUNNY', '구매 전 10초 멈춤 (추천)', 1),
  (84, 'RULE_HINT', 'ANY', '1장 룰', 2),
  (85, 'RULE_HINT', 'DRY', '‘더 사기’ 금지', 1),
  (86, 'RULE_HINT', 'FUNNY', '친구에게 선언', 3),
  (87, 'RULE_HINT', 'ANY', '친구에게 선언', 2),
  (88, 'RULE_HINT', 'COOL', '한도 고정', 1),
  (89, 'RULE_HINT', 'DRY', '집 가기 룰!', 2),
  (90, 'RULE_HINT', 'WARM', '친구에게 선언 🙂', 3),
  (91, 'RULE_HINT', 'ANY', '집 가기 룰', 1),
  (92, 'RULE_HINT', 'ANY', '집 가기 룰', 1),
  (93, 'RULE_HINT', 'WARM', '한도 고정!', 2),
  (94, 'RULE_HINT', 'FUNNY', '집 가기 룰 (추천)', 2),
  (95, 'RULE_HINT', 'WARM', '한도 고정 (추천)', 2),
  (96, 'RULE_HINT', 'COOL', '1장 룰', 3),
  (97, 'RULE_HINT', 'DRY', '한도 고정', 1),
  (98, 'RULE_HINT', 'DRY', '1장 룰!', 3),
  (99, 'RULE_HINT', 'WARM', '구매 전 10초 멈춤!', 2),
  (100, 'RULE_HINT', 'WARM', '집 가기 룰 (추천)', 2),
  (101, 'SIGNAL_POS', 'WARM', '도전 욕구가 건강하게 올라오는 부분 🙂', 3),
  (102, 'SIGNAL_POS', 'COOL', '컨디션이 꽤 괜찮은 편', 1),
  (103, 'SIGNAL_POS', 'FUNNY', '재정 신호가 여유 쪽으로 보이는 부분 (추천)', 1),
  (104, 'SIGNAL_POS', 'DRY', '컨디션이 꽤 괜찮은 편', 3),
  (105, 'SIGNAL_POS', 'WARM', '컨디션이 꽤 괜찮은 편 (추천)', 3),
  (106, 'SIGNAL_POS', 'COOL', '평정이 안정적으로 유지되는 흐름 (중요)', 1),
  (107, 'SIGNAL_POS', 'ANY', '도전 욕구가 건강하게 올라오는 부분', 1),
  (108, 'SIGNAL_POS', 'ANY', '낙관 쪽으로 기울어 있는 느낌', 3),
  (109, 'SIGNAL_POS', 'WARM', '컨디션이 꽤 괜찮은 편', 3),
  (110, 'SIGNAL_POS', 'DRY', '평정이 안정적으로 유지되는 흐름', 2),
  (111, 'SIGNAL_POS', 'DRY', '도전 욕구가 건강하게 올라오는 부분 (중요)', 2),
  (112, 'SIGNAL_POS', 'WARM', '컨디션이 꽤 괜찮은 편', 1),
  (113, 'SIGNAL_POS', 'FUNNY', '재정 신호가 여유 쪽으로 보이는 부분', 3),
  (114, 'SIGNAL_POS', 'WARM', '낙관 쪽으로 기울어 있는 느낌', 2),
  (115, 'SIGNAL_POS', 'FUNNY', '재정 신호가 여유 쪽으로 보이는 부분', 2),
  (116, 'SIGNAL_POS', 'FUNNY', '낙관 쪽으로 기울어 있는 느낌', 1),
  (117, 'SIGNAL_POS', 'DRY', '낙관 쪽으로 기울어 있는 느낌', 1),
  (118, 'SIGNAL_POS', 'FUNNY', '평정이 안정적으로 유지되는 흐름', 2),
  (119, 'SIGNAL_POS', 'COOL', '낙관 쪽으로 기울어 있는 느낌!', 1),
  (120, 'SIGNAL_POS', 'ANY', '컨디션이 꽤 괜찮은 편', 1),
  (121, 'SIGNAL_NEG', 'ANY', '스트레스가 소비로 번질 수 있는 위험 (중요)', 1),
  (122, 'SIGNAL_NEG', 'WARM', '지출이 부담으로 느껴질 수 있는 신호', 1),
  (123, 'SIGNAL_NEG', 'WARM', '스트레스가 소비로 번질 수 있는 위험', 2),
  (124, 'SIGNAL_NEG', 'ANY', '지출이 부담으로 느껴질 수 있는 신호', 2),
  (125, 'SIGNAL_NEG', 'WARM', '피로가 판단을 흐릴 수 있는 구간', 3),
  (126, 'SIGNAL_NEG', 'WARM', '피로가 판단을 흐릴 수 있는 구간', 1),
  (127, 'SIGNAL_NEG', 'DRY', '지출이 부담으로 느껴질 수 있는 신호', 1),
  (128, 'SIGNAL_NEG', 'WARM', '지출이 부담으로 느껴질 수 있는 신호', 1),
  (129, 'SIGNAL_NEG', 'DRY', '충동 버튼이 예민해질 수 있는 부분 🙂', 1),
  (130, 'SIGNAL_NEG', 'DRY', '충동 버튼이 예민해질 수 있는 부분', 1),
  (131, 'SIGNAL_NEG', 'FUNNY', '스트레스가 소비로 번질 수 있는 위험 (중요)', 2),
  (132, 'SIGNAL_NEG', 'FUNNY', '피로가 판단을 흐릴 수 있는 구간', 2),
  (133, 'SIGNAL_NEG', 'COOL', '피로가 판단을 흐릴 수 있는 구간', 2),
  (134, 'SIGNAL_NEG', 'COOL', '충동 버튼이 예민해질 수 있는 부분', 2),
  (135, 'SIGNAL_NEG', 'DRY', '스트레스가 소비로 번질 수 있는 위험', 3),
  (136, 'SIGNAL_NEG', 'FUNNY', '피로가 판단을 흐릴 수 있는 구간', 1),
  (137, 'SIGNAL_NEG', 'COOL', '안정감이 흔들릴 수 있는 지점 (중요)', 1),
  (138, 'SIGNAL_NEG', 'ANY', '스트레스가 소비로 번질 수 있는 위험 (추천)', 2),
  (139, 'SIGNAL_NEG', 'FUNNY', '안정감이 흔들릴 수 있는 지점', 2),
  (140, 'SIGNAL_NEG', 'WARM', '충동 버튼이 예민해질 수 있는 부분', 3),
  (141, 'STOP_RULE', 'ANY', '구매 후 바로 귀가!', 2),
  (142, 'STOP_RULE', 'ANY', '딱 1장만', 3),
  (143, 'STOP_RULE', 'WARM', '10초 멈춤 후 결정', 3),
  (144, 'STOP_RULE', 'FUNNY', '예산 넘으면 즉시 스톱!', 2),
  (145, 'STOP_RULE', 'FUNNY', '10초 멈춤 후 결정!', 2),
  (146, 'STOP_RULE', 'ANY', '오늘은 PASS (중요)', 1),
  (147, 'STOP_RULE', 'FUNNY', '예산 넘으면 즉시 스톱!', 3),
  (148, 'STOP_RULE', 'COOL', '한 번만 방문', 2),
  (149, 'STOP_RULE', 'ANY', '오늘은 PASS', 3),
  (150, 'STOP_RULE', 'FUNNY', '한 번만 방문 (추천)', 1),
  (151, 'STOP_RULE', 'WARM', '1회 구매 후 즉시 종료 (중요)', 3),
  (152, 'STOP_RULE', 'FUNNY', '한 번만 방문 🙂', 1),
  (153, 'STOP_RULE', 'COOL', '현금만 사용!', 3),
  (154, 'STOP_RULE', 'WARM', '친구에게 ‘끝’ 선언', 2),
  (155, 'STOP_RULE', 'FUNNY', '추가 구매 금지', 1),
  (156, 'STOP_RULE', 'DRY', '구매 후 바로 귀가 (중요)', 2),
  (157, 'STOP_RULE', 'WARM', '구매 후 바로 귀가', 1),
  (158, 'STOP_RULE', 'FUNNY', '현금만 사용', 1),
  (159, 'STOP_RULE', 'WARM', '오늘은 PASS', 2),
  (160, 'STOP_RULE', 'FUNNY', '딱 1장만', 1),
  (161, 'TIP_PHRASE', 'ANY', '로또를 사도 ‘1회 방문’만 하기', 3),
  (162, 'TIP_PHRASE', 'DRY', '로또를 사도 ‘1회 방문’만 하기', 2),
  (163, 'TIP_PHRASE', 'WARM', '오늘의 목표를 한 문장으로 쓰기', 3),
  (164, 'TIP_PHRASE', 'ANY', '기분 전환은 간식/산책으로 대체하기!', 1),
  (165, 'TIP_PHRASE', 'COOL', '한 장을 산 뒤 바로 멈추기', 2),
  (166, 'TIP_PHRASE', 'FUNNY', '‘더 살까?’가 오르면 즉시 멈추기', 1),
  (167, 'TIP_PHRASE', 'WARM', '구매 전 ‘오늘 한도’를 숫자로 적기 (추천)', 2),
  (168, 'TIP_PHRASE', 'ANY', '‘더 살까?’가 오르면 즉시 멈추기 (추천)', 2),
  (169, 'TIP_PHRASE', 'DRY', '구매 후 바로 다른 일정으로 이동하기!', 2),
  (170, 'TIP_PHRASE', 'DRY', '기분 전환은 간식/산책으로 대체하기', 2),
  (171, 'TIP_PHRASE', 'FUNNY', '‘더 살까?’가 오르면 즉시 멈추기!', 1),
  (172, 'TIP_PHRASE', 'COOL', '친구에게 오늘 룰을 공유하기', 3),
  (173, 'TIP_PHRASE', 'ANY', '지출 기록을 10초만 남기기 🙂', 2),
  (174, 'TIP_PHRASE', 'WARM', '‘더 살까?’가 오르면 즉시 멈추기 🙂', 1),
  (175, 'TIP_PHRASE', 'COOL', '‘더 살까?’가 오르면 즉시 멈추기', 2),
  (176, 'TIP_PHRASE', 'WARM', '지출 기록을 10초만 남기기 🙂', 1),
  (177, 'TIP_PHRASE', 'ANY', '한 장을 산 뒤 바로 멈추기', 3),
  (178, 'TIP_PHRASE', 'DRY', '‘더 살까?’가 오르면 즉시 멈추기', 2),
  (179, 'TIP_PHRASE', 'WARM', '친구에게 오늘 룰을 공유하기', 3),
  (180, 'TIP_PHRASE', 'FUNNY', '현금만 들고 나가기', 1),
  (181, 'CTA', 'WARM', '그대로 실행하면 오늘 리포트가 더 예쁘게 끝납니다', 2),
  (182, 'CTA', 'COOL', '그대로 실행하면 오늘 리포트가 더 예쁘게 끝납니다 (추천)', 3),
  (183, 'CTA', 'COOL', '해보면 의외로 만족도가 올라가요 🙂', 3),
  (184, 'CTA', 'ANY', '이 정도면 충분히 멋진 선택이에요', 3),
  (185, 'CTA', 'ANY', '이게 오늘의 핵심 안전장치예요', 1),
  (186, 'CTA', 'COOL', '이 정도면 충분히 멋진 선택이에요', 1),
  (187, 'CTA', 'DRY', '이 정도면 충분히 멋진 선택이에요', 1),
  (188, 'CTA', 'FUNNY', '이게 오늘의 핵심 안전장치예요', 2),
  (189, 'CTA', 'DRY', '오늘은 이걸로 게임 종료!', 3),
  (190, 'CTA', 'WARM', '이게 오늘의 핵심 안전장치예요 (중요)', 1),
  (191, 'CTA', 'DRY', '해보면 의외로 만족도가 올라가요', 3),
  (192, 'CTA', 'ANY', '오늘은 이걸로 게임 종료!', 3),
  (193, 'CTA', 'COOL', '이게 오늘의 핵심 안전장치예요 (중요)', 1),
  (194, 'CTA', 'ANY', '그대로 실행하면 오늘 리포트가 더 예쁘게 끝납니다', 1),
  (195, 'CTA', 'DRY', '이게 오늘의 핵심 안전장치예요', 1),
  (196, 'CTA', 'COOL', '이게 오늘의 핵심 안전장치예요', 2),
  (197, 'CTA', 'DRY', '이 정도면 충분히 멋진 선택이에요', 3),
  (198, 'CTA', 'COOL', '그대로 실행하면 오늘 리포트가 더 예쁘게 끝납니다', 3),
  (199, 'CTA', 'ANY', '이 정도면 충분히 멋진 선택이에요', 1),
  (200, 'CTA', 'COOL', '이게 오늘의 핵심 안전장치예요', 3);

INSERT INTO phrase_pool (id, slot_key, tone, text, weight) VALUES
  (201, 'CAUTION_PHRASE', 'ANY', '오늘은 자신에게 휴식을 주는 쪽이 좋아요', 2),
  (202, 'CAUTION_PHRASE', 'ANY', '오늘은 절제가 더 멋진 날이에요', 3),
  (203, 'CAUTION_PHRASE', 'COOL', '스트레스 해소용 구매는 오늘 특히 위험해요', 1),
  (204, 'CAUTION_PHRASE', 'FUNNY', '스트레스 해소용 구매는 오늘 특히 위험해요', 1),
  (205, 'CAUTION_PHRASE', 'COOL', '지갑이 타이트하면 재미도 부담이 돼요!', 1),
  (206, 'CAUTION_PHRASE', 'FUNNY', '지갑이 타이트하면 재미도 부담이 돼요 🙂', 2),
  (207, 'CAUTION_PHRASE', 'DRY', '오늘은 절제가 더 멋진 날이에요 (추천)', 1),
  (208, 'CAUTION_PHRASE', 'DRY', '과열되기 전에 멈추는 게 중요해요 (중요)', 1),
  (209, 'CAUTION_PHRASE', 'COOL', '오늘은 PASS가 더 현명할 수 있어요', 1),
  (210, 'CAUTION_PHRASE', 'COOL', '오늘은 작은 만족으로도 충분해요', 1),
  (211, 'CAUTION_PHRASE', 'ANY', '과몰입 신호가 감지됐어요!', 3),
  (212, 'CAUTION_PHRASE', 'WARM', '스트레스 해소용 구매는 오늘 특히 위험해요', 3),
  (213, 'CAUTION_PHRASE', 'DRY', '과몰입 신호가 감지됐어요', 1),
  (214, 'CAUTION_PHRASE', 'DRY', '오늘은 자신에게 휴식을 주는 쪽이 좋아요', 1),
  (215, 'CAUTION_PHRASE', 'FUNNY', '오늘은 자신에게 휴식을 주는 쪽이 좋아요 (추천)', 3),
  (216, 'CAUTION_PHRASE', 'WARM', '오늘은 작은 만족으로도 충분해요', 2),
  (217, 'CAUTION_PHRASE', 'DRY', '‘한 번 더’가 후회로 이어지기 쉬워요', 1),
  (218, 'CAUTION_PHRASE', 'DRY', '무리하면 즐거움이 급속히 떨어져요 (추천)', 3),
  (219, 'CAUTION_PHRASE', 'DRY', '과몰입 신호가 감지됐어요', 3),
  (220, 'CAUTION_PHRASE', 'COOL', '지갑이 타이트하면 재미도 부담이 돼요', 2),
  (221, 'BUDGET_SMALL', 'FUNNY', '딱 커피 한 잔 수준 🙂', 3),
  (222, 'BUDGET_SMALL', 'COOL', '‘한 장’ 가격만', 1),
  (223, 'BUDGET_SMALL', 'DRY', '0원(패스)', 3),
  (224, 'BUDGET_SMALL', 'DRY', '3,000원 이내 (추천)', 3),
  (225, 'BUDGET_SMALL', 'ANY', '3,000원 이내', 1),
  (226, 'BUDGET_SMALL', 'DRY', '작은 간식 정도', 3),
  (227, 'BUDGET_SMALL', 'WARM', '오늘은 최소로!', 1),
  (228, 'BUDGET_SMALL', 'DRY', '0원(패스)', 2),
  (229, 'BUDGET_SMALL', 'DRY', '1,000~2,000원 🙂', 3),
  (230, 'BUDGET_SMALL', 'ANY', '2,000~3,000원!', 2),
  (231, 'BUDGET_SMALL', 'COOL', '0원(패스)', 3),
  (232, 'BUDGET_SMALL', 'FUNNY', '딱 커피 한 잔 수준', 2),
  (233, 'BUDGET_SMALL', 'DRY', '지갑이 아프지 않은 선', 3),
  (234, 'BUDGET_SMALL', 'ANY', '오늘은 최소로', 1),
  (235, 'BUDGET_SMALL', 'COOL', '딱 커피 한 잔 수준', 1),
  (236, 'BUDGET_SMALL', 'FUNNY', '오늘은 최소로 🙂', 1),
  (237, 'BUDGET_SMALL', 'WARM', '오늘은 최소로 (추천)', 2),
  (238, 'BUDGET_SMALL', 'DRY', '오늘은 최소로', 3),
  (239, 'BUDGET_SMALL', 'FUNNY', '0원(패스)', 3),
  (240, 'BUDGET_SMALL', 'WARM', '지갑이 아프지 않은 선', 2),
  (241, 'FUN_THING', 'FUNNY', '물 한 컵 마시고 10번 호흡', 2),
  (242, 'FUN_THING', 'WARM', '스트레칭 2분 하기', 1),
  (243, 'FUN_THING', 'FUNNY', '좋아하는 노래 1곡 듣고 끝내기', 3),
  (244, 'FUN_THING', 'DRY', '스트레칭 2분 하기!', 1),
  (245, 'FUN_THING', 'ANY', '편의점에서 가장 작은 행운 간식 고르기', 1),
  (246, 'FUN_THING', 'COOL', '편의점에서 가장 작은 행운 간식 고르기', 3),
  (247, 'FUN_THING', 'WARM', '책상 위를 1분만 정리하기', 3),
  (248, 'FUN_THING', 'WARM', '5분 산책하며 ‘오늘 좋은 일 1개’ 찾기', 2),
  (249, 'FUN_THING', 'FUNNY', '좋아하는 노래 1곡 듣고 끝내기!', 1),
  (250, 'FUN_THING', 'WARM', '5분 산책하며 ‘오늘 좋은 일 1개’ 찾기', 2),
  (251, 'FUN_THING', 'FUNNY', '사진 한 장 찍기(하늘/거리)', 3),
  (252, 'FUN_THING', 'FUNNY', '책상 위를 1분만 정리하기 (추천)', 3),
  (253, 'FUN_THING', 'FUNNY', '오늘 감사한 것 1개 적기 🙂', 2),
  (254, 'FUN_THING', 'DRY', '내일 할 일 1개만 적고 종료', 3),
  (255, 'FUN_THING', 'ANY', '책상 위를 1분만 정리하기 (중요)', 2),
  (256, 'FUN_THING', 'FUNNY', '오늘 감사한 것 1개 적기', 1),
  (257, 'FUN_THING', 'COOL', '친구에게 응원 메시지 하나 보내기', 1),
  (258, 'FUN_THING', 'DRY', '책상 위를 1분만 정리하기 (중요)', 1),
  (259, 'FUN_THING', 'DRY', '물 한 컵 마시고 10번 호흡', 1),
  (260, 'FUN_THING', 'DRY', '좋아하는 노래 1곡 듣고 끝내기', 3),
  (261, 'STRATEGY_PHRASE', 'FUNNY', '한 장 후 바로 종료하는 단순 전략', 3),
  (262, 'STRATEGY_PHRASE', 'ANY', '현금만으로 제어하는 안전 전략', 1),
  (263, 'STRATEGY_PHRASE', 'DRY', '한 장 후 바로 종료하는 단순 전략 🙂', 3),
  (264, 'STRATEGY_PHRASE', 'DRY', '대체 행동을 준비해 충동을 분산하기', 3),
  (265, 'STRATEGY_PHRASE', 'WARM', '구매 강도는 낮게, 만족은 높게 (중요)', 2),
  (266, 'STRATEGY_PHRASE', 'DRY', '구매는 선택, 멈춤은 필수로 두기', 1),
  (267, 'STRATEGY_PHRASE', 'COOL', '한도 먼저 고정하고 그 안에서만 즐기기', 1),
  (268, 'STRATEGY_PHRASE', 'FUNNY', '구매는 선택, 멈춤은 필수로 두기', 2),
  (269, 'STRATEGY_PHRASE', 'DRY', '멈춤 규칙을 먼저 선언하고 시작하기', 1),
  (270, 'STRATEGY_PHRASE', 'WARM', '시간 창을 짧게 잡고 깔끔하게 끝내기', 1),
  (271, 'STRATEGY_PHRASE', 'COOL', '리포트를 보고도 ‘한 번 더’는 금지하기!', 1),
  (272, 'STRATEGY_PHRASE', 'FUNNY', '‘PASS 가능’ 옵션을 항상 열어두기', 1),
  (273, 'STRATEGY_PHRASE', 'WARM', '구매는 선택, 멈춤은 필수로 두기 🙂', 2),
  (274, 'STRATEGY_PHRASE', 'FUNNY', '한도 먼저 고정하고 그 안에서만 즐기기 (중요)', 2),
  (275, 'STRATEGY_PHRASE', 'COOL', '한도 먼저 고정하고 그 안에서만 즐기기', 1),
  (276, 'STRATEGY_PHRASE', 'COOL', '한 장 후 바로 종료하는 단순 전략', 3),
  (277, 'STRATEGY_PHRASE', 'ANY', '‘PASS 가능’ 옵션을 항상 열어두기', 3),
  (278, 'STRATEGY_PHRASE', 'COOL', '구매는 선택, 멈춤은 필수로 두기', 3),
  (279, 'STRATEGY_PHRASE', 'DRY', '시간 창을 짧게 잡고 깔끔하게 끝내기', 1),
  (280, 'STRATEGY_PHRASE', 'WARM', '대체 행동을 준비해 충동을 분산하기', 2),
  (281, 'TIME_WINDOW', 'COOL', '피곤할 때는 금지', 2),
  (282, 'TIME_WINDOW', 'ANY', '잠들기 전은 피하기', 2),
  (283, 'TIME_WINDOW', 'DRY', '약속 전후는 피하기', 3),
  (284, 'TIME_WINDOW', 'WARM', '맑을 때만 짧게', 1),
  (285, 'TIME_WINDOW', 'COOL', '약속 전후는 피하기!', 1),
  (286, 'TIME_WINDOW', 'DRY', '피곤할 때는 금지', 1),
  (287, 'TIME_WINDOW', 'DRY', '점심 전후 15분 (추천)', 1),
  (288, 'TIME_WINDOW', 'FUNNY', '피곤할 때는 금지', 3),
  (289, 'TIME_WINDOW', 'ANY', '기분이 안정된 시간에만', 1),
  (290, 'TIME_WINDOW', 'DRY', '집 가는 길에만 (추천)', 1),
  (291, 'TIME_WINDOW', 'FUNNY', '오늘은 한 번만', 3),
  (292, 'TIME_WINDOW', 'COOL', '피곤할 때는 금지', 2),
  (293, 'TIME_WINDOW', 'COOL', '피곤할 때는 금지', 3),
  (294, 'TIME_WINDOW', 'DRY', '점심 전후 15분', 3),
  (295, 'TIME_WINDOW', 'FUNNY', '약속 전후는 피하기 🙂', 3),
  (296, 'TIME_WINDOW', 'WARM', '집 가는 길에만', 2),
  (297, 'TIME_WINDOW', 'FUNNY', '퇴근길 10분', 3),
  (298, 'TIME_WINDOW', 'WARM', '오늘은 한 번만', 1),
  (299, 'TIME_WINDOW', 'WARM', '약속 전후는 피하기', 2),
  (300, 'TIME_WINDOW', 'FUNNY', '오늘은 한 번만', 2),
  (301, 'REASON_PHRASE', 'DRY', '만족도가 ‘룰’에서 결정되기 때문', 3),
  (302, 'REASON_PHRASE', 'FUNNY', '한도를 넘기면 재미가 부담이 되기 때문 🙂', 2),
  (303, 'REASON_PHRASE', 'ANY', '충동이 올라오면 판단이 흔들리기 때문 (중요)', 3),
  (304, 'REASON_PHRASE', 'COOL', '작은 성공 경험이 더 오래 가기 때문', 2),
  (305, 'REASON_PHRASE', 'DRY', '오늘은 안정감이 관건이기 때문', 3),
  (306, 'REASON_PHRASE', 'FUNNY', '만족도가 ‘룰’에서 결정되기 때문', 1),
  (307, 'REASON_PHRASE', 'COOL', '작은 성공 경험이 더 오래 가기 때문', 2),
  (308, 'REASON_PHRASE', 'WARM', '충동이 올라오면 판단이 흔들리기 때문 (중요)', 1),
  (309, 'REASON_PHRASE', 'DRY', '만족도가 ‘룰’에서 결정되기 때문', 3),
  (310, 'REASON_PHRASE', 'COOL', '오늘은 안정감이 관건이기 때문', 1),
  (311, 'REASON_PHRASE', 'DRY', '만족도가 ‘룰’에서 결정되기 때문', 2),
  (312, 'REASON_PHRASE', 'FUNNY', '만족도가 ‘룰’에서 결정되기 때문', 3),
  (313, 'REASON_PHRASE', 'ANY', '작은 성공 경험이 더 오래 가기 때문', 1),
  (314, 'REASON_PHRASE', 'COOL', '만족도가 ‘룰’에서 결정되기 때문', 2),
  (315, 'REASON_PHRASE', 'COOL', '충동이 올라오면 판단이 흔들리기 때문 (추천)', 1),
  (316, 'REASON_PHRASE', 'COOL', '한도를 넘기면 재미가 부담이 되기 때문', 3),
  (317, 'REASON_PHRASE', 'DRY', '충동이 올라오면 판단이 흔들리기 때문 (추천)', 1),
  (318, 'REASON_PHRASE', 'ANY', '작은 성공 경험이 더 오래 가기 때문', 1),
  (319, 'REASON_PHRASE', 'ANY', '한도를 넘기면 재미가 부담이 되기 때문', 3),
  (320, 'REASON_PHRASE', 'WARM', '한도를 넘기면 재미가 부담이 되기 때문', 3);
